### ISSUE TITLE
Support for Multiline Strings

### ISSUE THREAD

**Issue by Lonniebiz** [Fyrd/caniuse#2070] opened 2015-11-04 14:14 UTC
Example:

var text = `
This
Is
A
Multiline
String
`;

http://www.ecma-international.org/ecma-262/6.0/#sec-template-literal-lexical-components

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/template_strings

https://developers.google.com/web/updates/2015/01/ES6-Template-Strings?hl=en#multiline-strings

**Comment by Ugoku** [comment] 2015-11-19 13:01
+1

**Comment by ewoerner** [comment] 2017-12-28 14:15
This seems to be a duplicate of already implemented #2193?

**Comment by Lonniebiz** [comment] 2017-12-28 16:18
#2070 (this issue) was submitted on 11-04-2015. #2193 is a duplicate that was later submitted on 01-04-2016. Call me petty and I'll call you Betty!

**Comment by Fyrd** [comment] 2019-03-27 04:20
Added "multiline" as search keyword for https://caniuse.com/#feat=template-literals

**Closed by Fyrd** 2019-03-27 04:20 UTC
Labels: Support data suggestion
