### ISSUE TITLE
Add support for Image.decode

### ISSUE THREAD

**Issue by rockeynebhwani** [Fyrd/caniuse#4789] opened 2019-03-02 20:22 UTC
It will be good to get support for image.decode which is a useful feature (https://medium.com/dailyjs/image-loading-with-image-decode-b03652e7d2d2)

Also, refer
https://www.chromestatus.com/feature/5637156160667648

**Comment by Schweinepriester** [comment] 2019-03-04 19:32
Duplicate of #3902?

**Comment by Fyrd** [comment] 2019-03-06 07:03
Yup!

**Closed by Fyrd** 2019-03-06 07:03 UTC
Labels: Duplicate
