### ISSUE TITLE
add syncmanager

### ISSUE THREAD

**Issue by rlech** [Fyrd/caniuse#3579] opened 2017-07-07 11:39 UTC
https://wicg.github.io/BackgroundSync/spec/

**Comment by cvrebert** [comment] 2017-07-21 17:26
Duplicate of #2677?

**Comment by Fyrd** [comment] 2018-02-10 05:53
Yup, duplicate. Now available at https://caniuse.com/#feat=background-sync

**Closed by Fyrd** 2018-02-10 05:53 UTC
Labels: Duplicate, Support data suggestion
