### ISSUE TITLE
add overflow-style and marquee-style

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1255] opened 2015-05-12 05:07 UTC
add overflow-style and marquee-style

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+3__
Issue added by __kosmar__ on __2012-03-14__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment] 2015-05-19 07:09
Duplicate of #1499.

**Closed** 2015-05-20 03:16 UTC
Labels: GM import, Support data suggestion
