### ISSUE TITLE
image-rendering property

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1198] opened 2015-05-12 05:01 UTC
image-rendering property

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+7__
Issue added by __Alan Hogan__ on __2012-05-30__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment] 2015-05-20 05:53
Duplicate of #1246.

**Closed** 2015-05-21 03:50 UTC
Labels: GM import, Support data suggestion
