### ISSUE TITLE
there is no "white-space" css property in "can I use" website

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1425] opened 2015-05-12 06:01 UTC
there is no &quot;white-space&quot; css property in &quot;can I use&quot; website

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+4__
Issue added by __vsync__ on __2014-01-20__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment] 2015-05-19 03:44
Duplicate of #1262.

**Closed** 2015-05-19 03:48 UTC
Labels: GM import, Support data suggestion
