### ISSUE TITLE
Google Analytics Import OAuth Fails with Error 400: redirect_uri_mismatch

### ISSUE THREAD

**Issue by jboolean** [Fyrd/caniuse#6002] opened 2021-08-29 14:05 UTC
![Screen Shot 2021-08-29 at 10 03 46 AM](https://user-images.githubusercontent.com/406931/131253221-34d3c3e6-d0d4-4917-acd6-e88880180bc5.png)

OAuth appears to be misconfigured.

Using Opera Mac: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36 OPR/78.0.4093.147

**Comment by Fyrd** [comment] 2021-08-30 05:25
Thanks for reporting this. I _think_ this was probably caused by trying to access it via `www.caniuse.com`, which was not an approved domain. I've fixed the subdomain to always redirect to `caniuse.com` which I just tested and is working properly.

Can you try again?

**Comment by Fyrd** [comment] 2021-09-17 05:13
Closing this ticket as per my last comment.

**Closed by Fyrd** 2021-09-17 05:13 UTC
