### ISSUE TITLE
Web USB

### ISSUE THREAD

**Issue by awebdeveloper** [Fyrd/caniuse#3718] opened 2017-09-11 15:55 UTC
Include webusb 

https://blog.chromium.org/2017/08/chrome-61-beta-javascript-modules.html

https://developers.google.com/web/updates/2016/03/access-usb-devices-on-the-web

https://www.chromestatus.com/features/5651917954875392

https://webkit.org/status/#feature-webusb

**Comment by cvrebert** [comment] 2017-09-11 20:33
Duplicate of #2987

**Closed** 2017-09-12 07:43 UTC
