### ISSUE TITLE
Input event (oninput)  The input event is fired by <input> elements continuously as their valu...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1166] opened 2015-05-12 04:24 UTC
Input event (oninput)

The input event is fired by &lt;input&gt; elements continuously as their value changes. This makes it distinct from the change event which only fires when the &lt;input&gt; loses focus. This makes input useful for range controls.

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+8__
Issue added by __Ross S__ on __2014-11-14__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment] 2015-05-19 03:31
Duplicate of #1165.

**Closed** 2015-05-19 04:02 UTC
Labels: GM import, Support data suggestion
