### ISSUE TITLE
text-indent

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1125] opened 2015-05-12 04:21 UTC
text-indent

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+9__
Issue added by ____ on __2013-11-19__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment] 2015-05-19 04:14
Duplicate of #1065.

**Closed** 2015-05-19 04:15 UTC
Labels: GM import, Support data suggestion
