### ISSUE TITLE
Add Intersection Observer

### ISSUE THREAD

**Issue by gonzaloruizdevilla** [Fyrd/caniuse#2534] opened 2016-05-27 13:47 UTC
An API that can be used to understand movement of DOM elements relative to another element or the browser top level viewport. Changes are delivered asynchronously and are useful for understanding the visibility of elements, managing pre-loading of DOM and data, as well as deferred loading of "below the fold" page content.

https://developers.google.com/web/updates/2016/04/intersectionobserver?hl=en
https://github.com/WICG/IntersectionObserver/blob/master/explainer.md

**Comment by cvrebert** [comment] 2016-05-30 17:20
+1

**Comment by kostaldavid8** [comment] 2016-06-02 16:47
+1

**Comment by jrstanley** [comment] 2016-06-05 16:35
Duplicate of #2425

**Closed** 2016-06-05 16:40 UTC
Labels: Support data suggestion
