### ISSUE TITLE
display: run-in (

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1437] opened 2015-05-12 06:03 UTC
display: run-in (http://css-tricks.com/almanac/properties/d/display#run-in)

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+4__
Issue added by ____ on __2014-03-01__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment] 2015-05-20 06:03
Duplicate of #1369.

**Closed** 2015-05-21 03:51 UTC
Labels: GM import, Support data suggestion
