### ISSUE TITLE
include Transferable interface support for webworkers

### ISSUE THREAD

**Issue by LPCmedia** [Fyrd/caniuse#3252] opened 2017-03-20 05:29 UTC
need to know what browsers implement the transferable api for webworkers. 

see : 
https://developer.mozilla.org/en-US/docs/Web/API/Transferable

https://developers.google.com/web/updates/2011/12/Transferable-Objects-Lightning-Fast

https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers#Passing_data_by_transferring_ownership_(transferable_objects)

**Comment by Fyrd** [comment] 2017-03-20 06:05
Duplicate of #1132.

**Closed by Fyrd** 2017-03-20 06:05 UTC
