### ISSUE TITLE
Viewport description lacking clarity

### ISSUE THREAD

**Issue by anyotherway** [Fyrd/caniuse#1888] opened 2015-09-03 08:33 UTC
http://caniuse.com/#search=vw

Style operators like "border" are well understood, so topical brevity is OK. However, the four viewport beasts have just come in from 5 decades running wild, and never been tamed. You might want to make the description a little more helpful for wondering eyes. Suggestion:

Viewport units: vw, vh, vmin, vmax - CR
Length units representing 1% of total physical screen resource
Horizontal and vertical viewport measures width (vw), 
height (vh), the smaller of the two (vmin), or the larger of the two (vmax).

We cannot understand viewport unit measures, unless we know what viewport units are dedicated to measuring. It is dedication that makes these beasts difficult to manage! Properly managed, they are very predictable! 
Suggested re-write for vm, vh, vmin, vmax topic.

**Comment by cvrebert** [comment] 2015-09-04 03:23
Duplicate of #1886, albeit less rambling.

**Comment by Fyrd** [comment] 2015-09-04 03:34
This actually seems to be a suggestion to rewrite the description rather than a comment on the known issues. However I think it's sufficient the way it is, if people have trouble understanding what the viewport refers to they can find out more in the Resources section.

**Closed by Fyrd** 2015-09-04 03:34 UTC
