### ISSUE TITLE
Add QUIC

### ISSUE THREAD

**Issue by Zewy** [Fyrd/caniuse#3161] opened 2017-02-06 12:11 UTC
**QUIC, a multiplexed stream transport over UDP**
_QUIC is a new transport which reduces latency compared to that of TCP. On the surface, QUIC is very similar to TCP+TLS+HTTP/2 implemented on UDP. Because TCP is implemented in operating system kernels, and middlebox firmware, making significant changes to TCP is next to impossible. However, since QUIC is built on top of UDP, it suffers from no such limitations._

**Key features of QUIC over existing TCP+TLS+HTTP2 include** 

- Dramatically reduced connection establishment time
- Improved congestion control
- Multiplexing without head of line blocking
- Forward error correction
- Connection migration

https://www.chromium.org/quic

**Comment by Ugoku** [comment] 2017-02-06 13:06
Duplicate of #1752

**Comment by Zewy** [comment] 2017-02-07 14:11
https://www.chromestatus.com/feature/5338403830759424

QUIC
Network / Connectivity
An experimental, UDP-based QUIC transport protocol
Specification

Status in Chromium

Enabled by default in:
Chrome for desktop release 29
Opera release 16
Opera for Android release 16
Consensus & Standardization

Firefox: No public signals
Edge: No public signals
Safari: No public signals
Web Developers: No signals

**Closed** 2017-02-17 05:37 UTC
Labels: Duplicate
