### ISSUE TITLE
Email Client Compatibility

### ISSUE THREAD

**Issue by mattisherwood** [Fyrd/caniuse#2376] opened 2016-03-22 16:01 UTC
Feature request: Could you also have (perhaps grouped or tabbed together, another set of pages, or even on a sister site) the same search functionality as for browser support, but for email client support? (Such as [this info](https://www.campaignmonitor.com/css/))
Email client compatibility is obviously a **big** issue with designing/coding for email, and so this would be **hugely** helpful, I'm guessing to others as well as myself!

**Comment by cvrebert** [comment] 2016-03-23 19:54
Duplicate of #2017.

**Closed** 2016-03-31 03:43 UTC
Labels: Duplicate

**Comment by mattisherwood** [comment] 2016-03-31 14:09
Ah cheers, hadn't spotted that. Not to worry.
