### ISSUE TITLE
Add `color()` function from CSS Color Level 4

### ISSUE THREAD

**Issue by o-t-w** [Fyrd/caniuse#5424] opened 2020-05-12 20:39 UTC
There is already an issue about adding `lab()` and `lch()` but I would suggest that the `color()` function is documented separately as it has been supported by Safari stable already for a few years whereas no browser supports `lab()` or `lch()`.

**Comment by Schweinepriester** [comment] 2020-05-13 06:38
Duplicate of #3134?

**Comment by Fyrd** [comment] 2020-05-14 02:11
Yup!

**Closed by Fyrd** 2020-05-14 02:11 UTC
Labels: Duplicate
