### ISSUE TITLE
Add CSS L4 LAB Color space

### ISSUE THREAD

**Issue by paulhoule** [Fyrd/caniuse#5439] opened 2020-05-22 17:15 UTC
Designers of the world need to work sometimes with linear relative luminance and LAB lets you do that.  I want to see if and when it is in browsers.  Turns out LAB is the right color space if you need to do accessibility-related contrast calculations

**Comment by Fyrd** [comment] 2020-05-23 04:59
Looks like a duplicate of #5348

**Closed by Fyrd** 2020-05-23 04:59 UTC
Labels: Duplicate, Support data suggestion
