### ISSUE TITLE
window.visualViewport

### ISSUE THREAD

**Issue by crazy4groovy** [Fyrd/caniuse#3900] opened 2017-12-06 03:13 UTC
Can't find it in the list, but now supported by Chrome.

https://github.com/WICG/visual-viewport
http://www.creativebloq.com/features/15-web-apis-youve-never-heard-of/2

**Comment by cvrebert** [comment] 2017-12-06 06:01
Duplicate of #3638.

**Closed** 2017-12-06 06:02 UTC
Labels: Duplicate, Support data suggestion
