### ISSUE TITLE
New version of Samsung Internet browser

### ISSUE THREAD

**Issue by HeinPauwelyn** [Fyrd/caniuse#3452] opened 2017-05-22 09:16 UTC
Version 5 of Samsung Internet is released. The site is limited till version 4 of Samsung Internet. See this link: http://developer.samsung.com/internet

**Comment by Fyrd** [comment] 2017-05-26 02:41
Duplicate of https://github.com/Fyrd/caniuse/issues/3320 Currently looking into getting a way to test the browser, once I have that I'll add it.

**Closed by Fyrd** 2017-05-26 02:41 UTC
