### ISSUE TITLE
Add support for screen object

### ISSUE THREAD

**Issue by cakeant** [Fyrd/caniuse#4878] opened 2019-04-17 03:27 UTC
Please add support for screen object.
usage reference: https://www.w3schools.com/jsref/obj_screen.asp
I couldn't find a support list data for you, please let me know if there’s anything I can do to help.

**Comment by Fyrd** [comment] 2019-04-19 03:47
Duplicate of #1802

**Closed by Fyrd** 2019-04-19 03:47 UTC
Labels: Support data suggestion
