### ISSUE TITLE
Add document.activeElement()

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1168] opened 2015-05-12 04:24 UTC
Add document.activeElement()

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+8__
Issue added by __Nicolas McCurdy__ on __2014-05-27__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment] 2015-05-19 06:06
Duplicate of #1129.

**Closed** 2015-05-22 02:30 UTC
Labels: GM import, Support data suggestion
