### ISSUE TITLE
"webkit-overflow-scrolling" Safari has add this to iOS 5 to build applications with a more...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1426] opened 2015-05-12 06:02 UTC
&quot;webkit-overflow-scrolling&quot;
Safari has add this to iOS 5 to build applications with a more native feel.

http://developer.apple.com/library/safari/#documentation/appleapplications/reference/safaricssref/articles/standardcssproperties.html

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+4__
Issue added by __Anthony__ on __2012-04-11__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment] 2015-05-19 05:40
Duplicate of #1308.

**Closed** 2015-05-22 02:35 UTC
Labels: GM import, Support data suggestion
