### ISSUE TITLE
Add content-visibility?

### ISSUE THREAD

**Issue by oaustegard** [Fyrd/caniuse#5560] opened 2020-08-05 16:26 UTC
New Chrome 85 feature: https://web.dev/content-visibility/ - direct dependence on https://caniuse.com/#search=css-contain so maybe a redirect instead?

**Comment by Schweinepriester** [comment] 2020-08-06 08:35
Duplicate of #5559.

**Comment by devhelper** [comment] 2020-08-16 06:18
add content-visibility please

**Comment by JofunLiang** [comment] 2020-08-24 19:48
expect

**Comment by isaumya** [comment] 2020-08-27 08:55
Yes please add this. Both the `content-visibility` and `contain-intrinsic-size`. I have just now tried it on my stage site and honestly, the result was mind-blowing. This reduced my rendering time by 63.5% on the heaviest page. This is truly a great tool for web perf.

**Comment by ramiy** [comment] 2020-08-29 21:24
Chrome 85 added support for this CSS property.

See: https://developers.google.com/web/updates/2020/08/nic85#content-visibility

**Comment by scott8035** [comment] 2020-08-31 19:47
+1

**Comment by BeliefRC** [comment] 2020-09-02 15:09
+1

**Comment by PeterShershov** [comment] 2020-09-09 12:33
🙏

**Comment by mintymatt** [comment] 2020-09-21 13:32
🚀

**Comment by sungjoonlee** [comment] 2020-09-23 10:50
please

**Comment by Fyrd** [comment] 2020-09-25 04:44
Now available at https://caniuse.com/css-content-visibility

**Closed by Fyrd** 2020-09-25 04:44 UTC
Labels: Support data suggestion
