### ISSUE TITLE
Show support for X-Content-Type-Options header

### ISSUE THREAD

**Issue by ecki** [Fyrd/caniuse#3656] opened 2017-08-10 22:21 UTC
The header is `X-Content-Type-Options: nosniff` allows to protect against circumventing CSP and also helps against hot linking for some text based user serving sites (Github raw text view uses it to avoid high volume embedding)

**Comment by cvrebert** [comment] 2017-08-15 01:24
Duplicate of #2758

**Closed** 2017-08-15 01:36 UTC
