### ISSUE TITLE
HTMLInputElement API: select support

### ISSUE THREAD

**Issue by corymharper** [Fyrd/caniuse#5213] opened 2019-12-17 21:44 UTC
caniuse documents support for HTMLInputElement.setSelectionRange, but not for HTMLInputElement.select. I would like to see the addition of data regarding support for this feature of the API. Especially because MDN says, "for browsers that do not support this feature" which would imply there are browsers that do not support it.

https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/select

**Comment by GPHemsley** [comment] 2022-01-16 18:11
Looks like this is now covered by MDN data:
https://caniuse.com/mdn-api_htmlinputelement_select

(via mdn/browser-compat-data#7649)

**Comment by GPHemsley** [comment] 2022-01-17 03:30
Looks like this is a dupe of #2033.

**Closed** 2022-01-21 05:27 UTC
Labels: Support data suggestion
