### ISSUE TITLE
css unset:all

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1038] opened 2015-05-12 04:04 UTC
css unset:all

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+15__
Issue added by __matija__ on __2013-10-18__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment] 2015-05-19 04:04
Duplicate of #1059.

**Closed** 2015-05-19 04:09 UTC
Labels: GM import, Support data suggestion
