### ISSUE TITLE
 -webkit-scrollbar

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1037] opened 2015-05-12 04:04 UTC
-webkit-scrollbar

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+16__
Issue added by __egpierro__ on __2014-04-22__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by extempl** [comment] 2015-05-19 06:03
+1

**Comment by cvrebert** [comment] 2015-09-03 00:20
Duplicate of #1449.

**Closed** 2015-09-03 06:03 UTC
Labels: Duplicate, GM import, Support data suggestion
