### ISSUE TITLE
Should Safari for iPadOS and Safari for iOS be shown as different browsers?

### ISSUE THREAD

**Issue by daytonlowell** [Fyrd/caniuse#4996] opened 2019-07-09 19:07 UTC
Currently I know of at least 2 features that are available in iPadOS but not iOS:

Fullscreen API
Media Source Extensions

In PR #4995 I switched to showing partial support for Media Source Extensions on iOS because iOS 13 doesn't have it, but iPadOS 13 does. Thinking maybe breaking out iPadOS might be a good idea.

Thoughts?

**Comment by daytonlowell** [comment] 2019-07-09 19:10
Safari on iPadOS also disables `-webkit-overflow-scrolling: touch`

**Comment by Schweinepriester** [comment] 2019-07-09 20:56
Duplicate of #4946? ]:-> ;) :P

But seriously, I'm leaning more and more to separating Safari for iOS and iPadOS, as they are just not equal in their support anymore…

Safari for iPadOS features aren't equal to Safari for macOS either, or are they?
If they would be, iPadOS could be listed with macOS, but I dont think that is actually the case…?

**Comment by Schweinepriester** [comment] 2019-07-09 21:03
@daytonlowell 

Apologies, didnt mean for you to close the issue, I believe this one is better fit to discuss the differences :)

If you like, please reopen - or should I reopen #4946?

**Comment by kiding** [comment] 2019-07-11 01:08
I think #4946 has more context (and fyrd :wink:) on this. I'd reopen it, and close this issue.

**Comment by Fyrd** [comment] 2019-07-11 04:03
It's okay, I can keep an eye on more than one issue. ;)

I'll admit I'm not really fond of the idea of adding another browser column just because it has a few different features...the way I see it it's similar to browsers having some differences across Mac/Windows/Linux. There's differences across those OSes too and it would technically be more accurate to list them separately. However keeping the support overview simple in the majority of cases seems more valuable to me than an excess of information that will in most cases be duplicative.

So for now I think it's fine to continue listing differences as partial support. Will of course keep an eye on how big those changes become over time.

**Closed** 2019-07-11 14:13 UTC

**Comment by BEEDELLROKEJULIANLOCKHART** [comment] 2021-06-14 12:44
I believe that they should be considered to be different browsers.
