### ISSUE TITLE
Support table of ":has" pseudo CSS4 selector isn't exist.

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1511] opened 2015-05-12 06:12 UTC
Support table of &quot;:has&quot; pseudo CSS4 selector isn&#39;t exist.

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+3__
Issue added by __Pescao__ on __2015-02-04__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment] 2015-05-19 03:16
Duplicate of #1268

**Closed** 2015-05-19 03:54 UTC
Labels: GM import, Support data suggestion
