### ISSUE TITLE
<input type='tel'>

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1259] opened 2015-05-12 05:08 UTC
&lt;input type=&#39;tel&#39;&gt;

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+6__
Issue added by __Val__ on __2014-09-29__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment] 2015-05-19 03:34
Duplicate of #1097.

**Closed** 2015-05-19 03:37 UTC
Labels: GM import, Support data suggestion
