### ISSUE TITLE
DOMSubtreeModified

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1184] opened 2015-05-12 04:59 UTC
DOMSubtreeModified

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+7__
Issue added by __dom__ on __2015-01-14__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment] 2015-05-19 07:55
Duplicate of #1074.

**Closed** 2015-05-20 04:40 UTC
Labels: GM import, Support data suggestion
