### ISSUE TITLE
Check for TLS 1.3 Support

### ISSUE THREAD

**Issue by treyguinn** [Fyrd/caniuse#3322] opened 2017-04-05 23:09 UTC
Browser support for TLS 1.3 is emerging (Chrome and Firefox) and will be a significant differentiator.  Can this feature be included in the caniuse feature list?

**Comment by Schweinepriester** [comment] 2017-04-06 08:23
Duplicate of #2122.

**Closed** 2017-04-07 03:13 UTC
Labels: Duplicate
