### ISSUE TITLE
rudimentary info about a browser version's age

### ISSUE THREAD

**Issue by ccoenen** [Fyrd/caniuse#2062] opened 2015-11-01 09:27 UTC
Right now, with the short-cycled chrome and Firefox versions, they will stack up an impressive list of versions, while other browsers do not. It is sometimes hard to see "when" stuff was introduced to the browsers.

Let's say i want to know, when [ES5](http://caniuse.com/#feat=es5) got popular. I can see (with 'show all') that Firefox 21 and Chrome 23 supported it. But when was that? And which one was first? And when was IE10 released, anyway?

I know that market share is more important than age, but I'd still like to know sometimes.

**Comment by Fyrd** [comment] 2015-11-02 06:31
Duplicate of #202

**Closed by Fyrd** 2015-11-02 06:31 UTC
Labels: Duplicate

**Comment by ccoenen** [comment] 2015-11-02 08:16
Ooops, missed that one. Thanks!
