### ISSUE TITLE
Support for <button> attributes

### ISSUE THREAD

**Issue by LeartS** [Fyrd/caniuse#1905] opened 2015-09-08 09:48 UTC
It would be useful to add the compatibility table for the various form-related attributes of the button element: `formaction`, `formmethod`, `formenctype` etc. See [relevant MDN table](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#Browser_compatibility).

**Comment by cvrebert** [comment] 2015-09-08 20:48
Duplicate of #1562.
You should've found #1233 when searching the issues.

**Closed** 2015-09-09 03:34 UTC
Labels: Duplicate
