### ISSUE TITLE
Release Year on y axis?

### ISSUE THREAD

**Issue by tijanicharles** [Fyrd/caniuse#1767] opened 2015-07-29 17:26 UTC
Would be really cool if we could see the release dates alongside the browser versions. May help with better judgement of what features to implement.

**Comment by Fyrd** [comment] 2015-07-30 03:43
Duplicate of #202. Personally I feel the amount a version is being used (e.g. use the usage relative mode or the slider under Settings) is better for dictating whether or not it should be supported.

**Closed** 2015-07-30 03:43 UTC
Labels: Duplicate
