### ISSUE TITLE
Include capture attribute 

### ISSUE THREAD

**Issue by awebdeveloper** [Fyrd/caniuse#2133] opened 2015-12-06 15:04 UTC
input type="file" accept="video/*" capture

http://www.w3.org/TR/html-media-capture/

https://dev.opera.com/articles/media-capture-in-mobile-browsers/

**Comment by cvrebert** [comment] 2015-12-07 07:13
Duplicate of #1115.

**Closed** 2015-12-20 20:15 UTC
Labels: Duplicate
