### ISSUE TITLE
dash-offset

### ISSUE THREAD

**Issue by DerkJanSpeelman** [Fyrd/caniuse#3505] opened 2017-06-09 14:35 UTC

**Comment by Schweinepriester** [comment] 2017-06-09 15:20
Link? What is exactly meant? The similar property used in SVG?

**Comment by DerkJanSpeelman** [comment] 2017-06-09 15:34
The CSS value or XML+SVG attribute dash-offset

2017-06-09 17:20 GMT+02:00 Kai <notifications@github.com>:

**Comment by Schweinepriester** [comment] 2017-06-09 15:46
If this isn't a new one or something and <https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-dashoffset> is meant, this would be probably a duplicate of #1961, unless you want to find <https://caniuse.com/#feat=svg> by searching for `dash-offset`.

To put it another way: I don't seem to be able to find any information on a property exactly called `dash-offset`, expect for that smiliar SVG one.

**Comment by DerkJanSpeelman** [comment] 2017-06-09 15:49
Yes you are correct. I was searching for dash-array and dash-offset on
caniuse. And the attribute and the css property are basically the same.

**Comment by Fyrd** [comment] 2017-06-10 04:54
Yeah, duplicate of #1961, just misspelled.

**Closed by Fyrd** 2017-06-10 04:54 UTC
