### ISSUE TITLE
Hyperlink auditing / ping attribute on a link  

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1183] opened 2015-05-12 04:59 UTC
Hyperlink auditing / ping attribute on a link

http://www.whatwg.org/specs/web-apps/current-work/multipage/links.html#hyperlink-auditing

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+7__
Issue added by __Bryan__ on __2011-11-06__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment] 2015-05-19 07:56
Duplicate of #1172.

**Closed** 2015-05-20 04:42 UTC
Labels: GM import, Support data suggestion
