### ISSUE TITLE
'sortable' global attribute, table

### ISSUE THREAD

**Issue by anyotherway** [Fyrd/caniuse#2701] opened 2016-08-07 22:38 UTC
caniuse needs to add global attribute ' `sortable` '

**sortable (sortable="sortable" _in XHTML_)**
WHATWG & HTML5.1 only. When present, it indicates the table's contents may be sorted by column. It is used in conjunction with the `sorted` attribute on the `th` element, which can be set manually or by the user agent when the user clicks a column.

HTML5 Pocket Reference, 5th Edition, O'Reilly, C 2013 - page 135.
Table > Attributes > _HTML5 Global Attributes_

**Comment by cvrebert** [comment] 2016-08-07 22:46
Duplicate of #2437.

**Comment by anyotherway** [comment] 2016-08-07 23:51
2437 is closed (?) GitHub needs a Public view of Admin, with Google access. O'Reilly description iis a start - _Jennifer Niederst Robbins_. More on `sorted`...

**sorted (sortable="sortable" _in XHTML_)**
"reversed | number | reversed number | number reversed | number greater than zero".
**WHATWG & HTML5.1 only**. Provides a means for users to sort table columns in tables with the sortable attribute.

HTML5 Pocket Reference, 5th Edition, O'Reilly, C 2013 - page 135.
Table > Attributes > _HTML5 Global Attributes_

**Note**. Sorted variable options include those found today at W#Schools.com. One wonders where _sort_ attributes are going without an alphabetical sort mentioned anywhere. Attribute `width` is adopted for `<th>`, while `sorted` and `sortable` are still missing. Perhaps `scope` is issue.

**Scope**. Consider the CSS3 Colors table at CssPortal.
[http://www.cssportal.com/css3-color-names/](http://www.cssportal.com/css3-color-names/).
Each row 'scopes' particular and exclusive values. Sorting any header's sort attribute must also maintain each color's data scope.
[http://www.w3schools.com/tags/att_th_scope.asp](http://www.w3schools.com/tags/att_th_scope.asp).

**Comment by Fyrd** [comment] 2016-08-17 05:39
Yeah, closing as duplicate. No need to add features that haven never been nor will be supported.

**Closed** 2016-08-17 05:38 UTC
Labels: Duplicate

**Comment by anyotherway** [comment] 2016-12-25 09:04
Rather bold comment Fyrd. From a very tiny corner of the Internet Of Things. Inclusive is not repetition, is reaching for a new topic. Cope and contribute, rather than condescend.
