### ISSUE TITLE
requestIdleCallback

### ISSUE THREAD

**Issue by zeh-workco** [Fyrd/caniuse#1992] opened 2015-09-29 18:00 UTC
API allowing scheduling code to be executed when there is free time at the end of a frame, or when the user is inactive.

Shipping on Chrome 47: https://developers.google.com/web/updates/2015/08/27/using-requestidlecallback?hl=en

Editor's draft: https://w3c.github.io/requestidlecallback/

**Comment by cvrebert** [comment] 2015-09-29 23:16
Duplicate of #1848. Try searching next time.

**Comment by zeh-workco** [comment] 2015-09-29 23:32
@cvrebert: sorry for the duplicate. Thanks for checking it.

For the record, I did a search, and couldn't find the issue yet. However, I didn't know GitHub's issue search didn't match partial words:

![image](https://cloud.githubusercontent.com/assets/13369058/10180984/ad68e7ce-66e0-11e5-8540-4bd0bed6cf2a.png)

That might be worth taking into consideration if you're seeing too many duplicate issues.

**Closed** 2015-09-29 23:33 UTC
