### ISSUE TITLE
Custom scrollbars. Supported in webkit browsers only at the moment.  

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1120] opened 2015-05-12 04:20 UTC
Custom scrollbars. Supported in webkit browsers only at the moment.

http://css-tricks.com/custom-scrollbars-in-webkit/

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+10__
Issue added by ____ on __2012-08-15__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by extempl** [comment] 2015-05-19 06:03
+1

**Comment by cvrebert** [comment] 2015-05-19 06:28
-1

**Comment by cvrebert** [comment] 2015-09-02 22:57
Duplicate of #1449.

**Closed** 2015-09-03 06:05 UTC
Labels: Duplicate, GM import, Support data suggestion
