### ISSUE TITLE
DOM node property textContent

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1289] opened 2015-05-12 05:11 UTC
DOM node property textContent

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+5__
Issue added by __@npup__ on __2011-12-01__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment] 2015-05-19 04:13
Duplicate of #1056.

**Closed** 2015-05-19 04:14 UTC
Labels: GM import, Support data suggestion
