### ISSUE TITLE
There is no result for "display : inline flow-root" and others

### ISSUE THREAD

**Issue by Tenebrosful1** [Fyrd/caniuse#5612] opened 2020-09-16 15:15 UTC
Hi,

When i search about `inline flow`, `block flow`, `inline flow-root`, `block flow-root` which are new syntax for `inline` `block` `inline-block` `flow-root` for `display` CSS3 i have no result for browsers compatibility

**Comment by Fyrd** [comment] 2020-09-17 04:17
Looks like a duplicate of #5147

**Closed by Fyrd** 2020-09-17 04:17 UTC
Labels: Duplicate
