### ISSUE TITLE
Date.now() 

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1451] opened 2015-05-12 06:05 UTC
Date.now()
http://kangax.github.io/es5-compat-table/#Date.now

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+3__
Issue added by __Aaron__ on __2014-03-16__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment] 2015-05-19 04:19
Duplicate of #1118.

**Closed** 2015-05-19 04:27 UTC
Labels: GM import, Support data suggestion
