### ISSUE TITLE
Portals API

### ISSUE THREAD

**Issue by ThomasFeyrer** [Fyrd/caniuse#5195] opened 2019-11-25 13:06 UTC
New API from Google:

https://web.dev/hands-on-portals/

https://www.zdnet.com/article/google-launches-portals-a-new-web-page-navigation-system-for-chrome/

In which we make loading disappear with 'portal' and friends (Chrome Dev Summit 2019)
https://www.youtube.com/watch?v=X2zqwMBBvIs

**Comment by Schweinepriester** [comment] 2019-11-26 16:06
Duplicate of #4679.

That issue could use the string "Portals API" for better visibility as well as the second and third URL though.

**Closed** 2020-05-25 06:10 UTC
Labels: Duplicate, Support data suggestion
