### ISSUE TITLE
Bi-Directional Isolation Element 

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1327] opened 2015-05-12 05:16 UTC
Bi-Directional Isolation Element
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/bdi

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+5__
Issue added by __bkaplan__ on __2014-06-10__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment] 2015-05-19 07:23
Duplicate of #1131.

**Closed** 2015-05-20 03:22 UTC
Labels: GM import, Support data suggestion
