### ISSUE TITLE
Web NFC

### ISSUE THREAD

**Issue by awebdeveloper** [Fyrd/caniuse#3719] opened 2017-09-11 16:05 UTC
include web nfc

https://www.chromestatus.com/features/6261030015467520

https://developer.microsoft.com/en-us/microsoft-edge/platform/catalog/?q=specName%3Aweb-nfc

https://www.w3.org/TR/nfc/

**Comment by cvrebert** [comment] 2017-09-11 20:33
Duplicate of #2085
Try searching more in the future?

**Closed** 2017-09-12 07:42 UTC
