### ISSUE TITLE
The <output> tag is missing

### ISSUE THREAD

**Issue by wamoyo** [Fyrd/caniuse#2616] opened 2016-06-30 16:41 UTC
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/output

It's actually kind of helpful. Especially if you're building something like html5 video controls, and you want to show the time in the seekbar.

**Comment by cvrebert** [comment] 2016-07-01 20:38
Duplicate of #1107.

**Closed** 2016-07-03 22:15 UTC
Labels: Duplicate
