### ISSUE TITLE
navigator.connection

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1488] opened 2015-05-12 06:09 UTC
navigator.connection

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+3__
Issue added by __grigs__ on __2012-02-02__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment] 2015-05-19 07:16
Duplicate of #1031.

**Closed** 2015-05-20 03:19 UTC
Labels: GM import, Support data suggestion
