### ISSUE TITLE
css cross-fade  

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1462] opened 2015-05-12 06:06 UTC
css cross-fade

https://docs.webplatform.org/wiki/css/functions/cross-fade

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+3__
Issue added by __Rob__ on __2015-03-24__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment] 2015-05-20 06:10
Duplicate of #1219.

**Closed** 2015-05-21 03:52 UTC
Labels: GM import, Support data suggestion
