### ISSUE TITLE
HTMLCanvasElement.toBlob()

### ISSUE THREAD

**Issue by nokite** [Fyrd/caniuse#1990] opened 2015-09-28 14:52 UTC
HTMLCanvasElement.toBlob() support should be described. Check https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob for instance

**Comment by Fyrd** [comment] 2015-09-29 03:39
Duplicate of #1496, please add your vote there.

**Closed by Fyrd** 2015-09-29 03:39 UTC
