### ISSUE TITLE
<a ping  The <a> tag's `ping` attribute silently notifies a URL when a link has been cl...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1134] opened 2015-05-12 04:21 UTC
&lt;a ping

The &lt;a&gt; tag&#39;s `ping` attribute silently notifies a URL when a link has been clicked. It was mentioned in Google.IO 2012 and currently has staggered support. It&#39;d be great to see its usage!

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+9__
Issue added by __Qix__ on __2014-09-11__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment] 2015-05-19 06:30
-1

**Comment by cvrebert** [comment] 2015-05-19 07:56
Duplicate of #1172.

**Closed** 2015-05-20 04:42 UTC
Labels: GM import, Support data suggestion
