### ISSUE TITLE
`font-display` for `@font-face`

### ISSUE THREAD

**Issue by tibor** [Fyrd/caniuse#2761] opened 2016-08-27 15:19 UTC
`font-display` is a rather new property which can be used in `@font-face` declarations to give the browser a hint if fallback fonts shall be used until the font is loaded.

It’s a CSS only solution for scripts like WebFontLoader or FontFaceObserver.

**Comment by cvrebert** [comment] 2016-08-28 06:46
Spec: https://tabatkins.github.io/specs/css-font-display/#font-display-desc

**Comment by Fyrd** [comment] 2016-08-29 09:59
Duplicate of #2001

**Closed by Fyrd** 2016-08-29 09:59 UTC
