### ISSUE TITLE
Missing versions in data.json

### ISSUE THREAD

**Issue by iamvdo** [Fyrd/caniuse#893] opened 2015-02-18 10:05 UTC
Since this commit 64ba5d962d91b4e822f00a3c7ee3c7d30453bcf7, it misses versions of browsers in `data.json`. For example, in `agents.opera.versions`, it no longer contains Opera 12 and many others. `null` is used instead.

Is it expected ?

**Comment by iamvdo** [comment] 2015-02-18 10:18
"Problem" appear in version `1.0.30000066`

**Comment by ai** [comment] 2015-02-18 16:22
Opera 12 is still actual, because many users in Russia uses it.

/cc @pepelsbey

**Comment by ai** [comment] 2015-02-18 16:22
@Fyrd Opera 12 is still actual, because many users in Russia uses it.

/cc @pepelsbey

**Comment by Fyrd** [comment] 2015-02-19 03:58
Yeah, I thought I'd start removing more versions that are barely anymore. This was intended to just be for the site though, I forgot it'd occur on the data too, so I apologize for that. Will try to get it back soon.

@ai According to my StatCounter-processed data Opera 12 is only used by 0.26% of people of Russia, so I wouldn't call that "many users". You may be thinking of 12.1, which indeed is used more and is still included.

**Comment by Fyrd** [comment] 2015-02-19 04:18
Fixed in 4bc3efad99d3c2dd87884462f3e2089dc1f2e4b2

**Closed by Fyrd** 2015-02-19 04:18 UTC

**Comment by ai** [comment] 2015-02-19 08:50
@Fyrd [according to statscounter](http://gs.statcounter.com/#browser_version_partially_combined-RU-monthly-201401-201501-bar) Opera 12.1 has 4.43 % in Russia. More popular, that iPad and IE 8, 9, 10.

**Comment by Fyrd** [comment] 2015-02-19 16:20
@ai I'm well aware of this. That's why I said "You may be thinking of 12.1, which indeed is used more and is still included"
