### ISSUE TITLE
Add asyncIterator

### ISSUE THREAD

**Issue by itayronen** [Fyrd/caniuse#4319] opened 2018-06-19 19:15 UTC
https://github.com/tc39/proposal-async-iteration
Copying the from the above link:
### Native implementations
Chakra: outstanding issue
JavaScriptCore: shipping in Safari Tech Preview 40
SpiderMonkey: shipping in Firefox 57; launch bug
V8: shipping in Chrome 63; launch bug

I personally have Chrome 66 and I can confirm:
* It has the asyncIterator symbol (Symbol.asyncIterator).
* async generator syntax works: "async function* myFunction()...".
* Not sure about "for await (...)".

**Comment by Schweinepriester** [comment] 2018-06-21 15:17
Duplicate of #3690?

**Comment by Fyrd** [comment] 2018-06-23 21:05
Yup, duplicate. Data's available and pending review, may add this one soon.

**Closed by Fyrd** 2018-06-23 21:05 UTC
Labels: Duplicate
