### ISSUE TITLE
Add 'prefers-color-scheme media query' feature

### ISSUE THREAD

**Issue by daytonlowell** [Fyrd/caniuse#4581] opened 2018-10-24 18:13 UTC
Spec: https://drafts.csswg.org/mediaqueries-5/#prefers-color-scheme

Also this is supported in Safari Technology Preview on macOS Mojave: https://webkit.org/blog/8475/release-notes-for-safari-technology-preview-68/

**Comment by Schweinepriester** [comment] 2018-10-24 20:11
Duplicate of #4514.

**Closed** 2018-10-26 05:47 UTC
Labels: Duplicate
