### ISSUE TITLE
Add Array.prototype.flatMap

### ISSUE THREAD

**Issue by shuch** [Fyrd/caniuse#4639] opened 2018-11-27 01:34 UTC
add support for [Array.prototype.flatMap()
](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Array/flatMap)

**Comment by cpplearner** [comment] 2018-11-27 02:58
duplicate of #4294?

**Comment by shuch** [comment] 2018-11-28 01:00
the same with [#4294](https://github.com/Fyrd/caniuse/issues/4294)

**Closed** 2018-12-14 05:17 UTC
Labels: Duplicate
