### ISSUE TITLE
box-decoration-break 

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1169] opened 2015-05-12 04:24 UTC
box-decoration-break
https://developer.mozilla.org/en-US/docs/Web/CSS/box-decoration-break

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+8__
Issue added by __edward_sch__ on __2014-09-16__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment] 2015-05-19 08:51
Duplicate of #1281.

**Closed** 2015-05-20 03:24 UTC
Labels: GM import, Support data suggestion
