### ISSUE TITLE
Add support for "draggable" attribute

### ISSUE THREAD

**Issue by filipefmelo** [Fyrd/caniuse#3059] opened 2016-12-20 12:13 UTC
Hi, I was looking for help regarding the "draggable" attribute but did not find it in the website.
It can be found here: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/draggable

**Comment by Schweinepriester** [comment] 2016-12-21 10:42
Covered by http://caniuse.com/#feat=dragndrop and/or duplicate of #1807 or #2673?

**Comment by Fyrd** [comment] 2017-01-11 06:05
Yeah, I'll say duplicate of #1807, probably warrants at least investigation of the attribute.

**Closed by Fyrd** 2017-01-11 06:05 UTC
