### ISSUE TITLE
TrustedTypes API

### ISSUE THREAD

**Issue by toklok** [Fyrd/caniuse#4867] opened 2019-04-11 13:23 UTC
https://github.com/WICG/trusted-types

I know this is super new and only works in Chrome Experimental, but this would be good to have once browsers start implementing this.

**Comment by Malvoz** [comment] 2019-04-11 16:02
This is a duplicate of https://github.com/Fyrd/caniuse/issues/4787. ^^

**Closed** 2019-04-11 17:37 UTC
