### ISSUE TITLE
Add CSS font-synthesis

### ISSUE THREAD

**Issue by averoigne** [Fyrd/caniuse#3425] opened 2017-05-10 10:22 UTC

**Comment by Flimm** [comment] 2018-02-27 13:07
This is a duplicate of https://github.com/Fyrd/caniuse/issues/1799

**Comment by Fyrd** [comment] 2020-06-13 23:40
Yup, available at https://caniuse.com/#feat=mdn-css_properties_font-synthesis

**Closed by Fyrd** 2020-06-13 23:40 UTC
Labels: Support data suggestion
