### ISSUE TITLE
Add web assembly/wasm

### ISSUE THREAD

**Issue by kanaka** [Fyrd/caniuse#2099] opened 2015-11-19 17:56 UTC
Related to asm.js but should probably be called out separately.

Links:
- https://brendaneich.com/2015/06/from-asm-js-to-webassembly/
- http://www.2ality.com/2015/06/web-assembly.html
- https://github.com/WebAssembly
- https://github.com/WebAssembly/design
- https://github.com/WebAssembly/spec
- https://github.com/WebAssembly/wasm-e2e
- https://www.chromestatus.com/features#Webassembly (proposed status for Chrome)

**Comment by cvrebert** [comment] 2015-11-22 09:26
Duplicate of #1674.

**Comment by Fyrd** [comment] 2020-03-25 04:08
This was added some time ago at https://caniuse.com/#feat=wasm

**Closed by Fyrd** 2020-03-25 04:08 UTC
Labels: Support data suggestion
