### ISSUE TITLE
Support Web Authentication

### ISSUE THREAD

**Issue by lakano** [Fyrd/caniuse#3838] opened 2017-11-07 11:40 UTC
Hi,
Thanks for this essential website!
Could you add the support for [Web Authentication](https://w3c.github.io/webauthn/) please? 

The W3C have [a blog dedied](https://www.w3.org/blog/webauthn/) and [a mailing-list](https://lists.w3.org/Archives/Public/public-webauthn/) to follow this feature.

[Google Chrome partial support](https://bugs.chromium.org/p/chromium/issues/detail?id=664630).
[Mozilla Firefox partial support](https://wiki.mozilla.org/Security/CryptoEngineering#Web_Authentication)
[Microsoft Edge partial support](https://developer.microsoft.com/en-us/microsoft-edge/platform/documentation/dev-guide/device/web-authentication/)
[Apple Safari support under consideration](https://webkit.org/status/#feature-web-authentication)
No information found about Opera support.

FIDO U2F API should be in theory be replaced/moved to Web Authentication (formerly known as FIDO 2.0)
Regards,

**Comment by Fyrd** [comment] 2017-11-08 03:21
Duplicate of #2423.

**Closed by Fyrd** 2017-11-08 03:21 UTC
Labels: Duplicate
