### ISSUE TITLE
Every feature is reported as 1.8% less supported than it really is!

### ISSUE THREAD

**Issue by jensimmons** [Fyrd/caniuse#6933] opened 2023-12-29 15:40 UTC
100% support is listed as 98%.
96% support is listed as 94%.
91% support is listed as 89%.
It's impossible for anything to be fully supported.

**This is a duplicate issue who's only purpose is to get more attention on this issue.
https://github.com/Fyrd/caniuse/issues/6733**

(Do close it once you see this issue from June needs to be addressed.)

**Comment by Fyrd** [comment] 2024-01-02 07:05
I believe this is actually a duplicate of #6813.

The reason it does not display 100% is because there are some browsers & versions reported by StatCounter are not tracked on caniuse. You can see this list at the bottom of the [usage table](https://caniuse.com/usage-table). When a browser is not tracked the support is unknown and therefore not included in this total.

There's a "?" button and dropdown list in the usage header to help explain this, though perhaps this could be improved:
<img width="460" alt="Screen Shot 2024-01-01 at 10 53 02 PM" src="https://github.com/Fyrd/caniuse/assets/432336/db8d6009-46fe-4aea-9f44-31e27338a576">

The dropdown list allows the calculation to be changed to "All tracked" which ignores any browsers not on caniuse and results in the percentage you're looking for.

The reason I prefer "all users" to be the default is because it seems more prudent to acknowledge that there's a few % of users out there using less common browsers which deserve consideration as well. There may also be certain regions where such browsers are more common so I'd rather not ignore them entirely.

**Comment by SebastianZ** [comment] 2024-01-03 10:26
> I believe this is actually a duplicate of #6813.

So let's close it as duplicate then to avoid duplicate discussions.

Sebastian

**Closed** 2024-01-04 06:50 UTC
Labels: Duplicate
