### ISSUE TITLE
CSS Namespaces  

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1081] opened 2015-05-12 04:17 UTC
CSS Namespaces 
http://www.w3.org/TR/css3-namespace/

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+12__
Issue added by __Ryan M__ on __2011-11-07__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment] 2015-05-19 04:17
Duplicate of #1054.

**Closed** 2015-05-19 04:27 UTC
Labels: GM import, Support data suggestion
