### ISSUE TITLE
Add support for CSS rule @document

### ISSUE THREAD

**Issue by velara3** [Fyrd/caniuse#3671] opened 2017-08-20 03:55 UTC
Searching for the CSS rule "@document" comes up blank. 

https://www.quackit.com/css/at-rules/css_document_at-rule.cfm
https://www.w3.org/TR/2012/WD-css3-conditional-20120911/#at-document
https://www.w3.org/TR/2012/WD-css3-conditional-20121213/#changes

**Comment by Fyrd** [comment] 2019-03-27 05:01
Duplicate of #2588

**Closed by Fyrd** 2019-03-27 05:01 UTC
Labels: Duplicate, Support data suggestion
