### ISSUE TITLE
Add overscroll-behaviour

### ISSUE THREAD

**Issue by gurmukhp** [Fyrd/caniuse#3866] opened 2017-11-22 10:23 UTC
Please would it be possible to add the overscroll-behaviour feature?

https://developers.google.com/web/updates/2017/11/overscroll-behavior?utm_source=CSS-Weekly&utm_campaign=Issue-290&utm_medium=email

**Comment by Malvoz** [comment] 2017-11-22 11:48
[Duplicate of #3725 ](https://github.com/Fyrd/caniuse/issues/3725)

**Closed** 2017-11-23 05:43 UTC
Labels: Duplicate
