### ISSUE TITLE
Hi, 2 things: 1. ElementFromPoint is interesting & has odd behavior in Firefox. 2. Your own &quo...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1537] opened 2015-05-12 06:15 UTC
Hi, 2 things:
1. ElementFromPoint is interesting &amp; has odd behavior in Firefox.
2. Your own &quot;Suggest this feature to be added&quot; is broken.

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+3__
Issue added by __snadrus__ on __2014-01-21__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment] 2015-05-19 03:35
Duplicate of #1193.

**Closed** 2015-05-19 03:37 UTC
Labels: GM import, Support data suggestion

**Comment by techsin** [comment] 2015-05-24 14:43
+1
