### ISSUE TITLE
Bug in caniuse.com website

### ISSUE THREAD

**Issue by crisz** [Fyrd/caniuse#4891] opened 2019-04-23 14:37 UTC
I don't know if this is the correct place to open this issue, but this is the only repository connected to the website.

The bug is the following, clicking the "enable accessible colors" button on the bottom of the page, the summary goes from this:

[![enter image description here][1]][1]

to this:

[![enter image description here][2]][2]

Is this a joke? :D

This is obviously a bug, because clicking the "use default colors" again, it remains gray.

I verified the problem with Chorme 73.0.3683.103 and Mac OS X

  [1]: https://i.stack.imgur.com/sbukw.png
  [2]: https://i.stack.imgur.com/yxwTI.png

**Comment by Malvoz** [comment] 2019-04-23 19:57
Works fine for me in the same version of Chrome on Windows.

**Comment by Fyrd** [comment] 2019-04-24 04:22
Duplicate of #1745

Not sure what part you think is a joke? The shades of gray help indicate the degrees of support without depending on specific colors, seemed the easiest to implement while working for the different types of colorblindness.

**Closed by Fyrd** 2019-04-24 04:22 UTC

**Comment by crisz** [comment] 2019-04-24 07:40
Ok if it is intended, I'm not an expert of color blindness and I'm sorry for that. By the way, the button to reset default colors still don't work. You can for example search "grid" and then click two times the button
