### ISSUE TITLE
addEventListener and removeEventListener

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1318] opened 2015-05-12 05:15 UTC
addEventListener and removeEventListener

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+5__
Issue added by __Michael__ on __2014-09-30__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment] 2015-05-19 03:32
Duplicate of #1250.

**Closed** 2015-05-19 03:46 UTC
Labels: GM import, Support data suggestion
