### ISSUE TITLE
bdi stands for Bi-directional Isolation. New feature implemented in FF 10

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1263] opened 2015-05-12 05:08 UTC
bdi stands for Bi-directional Isolation. New feature implemented in FF 10

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+6__
Issue added by __Denis V__ on __2012-01-31__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment] 2015-05-19 06:07
Duplicate of #1131.

**Closed** 2015-05-20 03:22 UTC
Labels: GM import, Support data suggestion
