### ISSUE TITLE
activeElement

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1178] opened 2015-05-12 04:58 UTC
activeElement

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+7__
Issue added by __spurv__ on __2013-05-03__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment] 2015-05-19 06:06
Duplicate of #1129.

**Comment by cvrebert** [comment] 2015-05-21 22:44
@Fyrd Please close as duplicate.

**Closed** 2015-05-22 02:30 UTC
Labels: GM import, Support data suggestion
