### ISSUE TITLE
Add CSS text-orientation property 

### ISSUE THREAD

**Issue by yisibl** [Fyrd/caniuse#2158] opened 2015-12-17 12:12 UTC
https://developer.mozilla.org/en-US/docs/Web/CSS/text-orientation

**Comment by Ugoku** [comment] 2015-12-17 14:49
+1

**Comment by Fyrd** [comment] 2015-12-21 23:17
Duplicate of #2077

**Closed by Fyrd** 2015-12-21 23:17 UTC

**Comment by iGadget73** [comment] 2017-01-10 10:23
+ 1
