### ISSUE TITLE
html5 input event support!  it works a lot nicer than keyup or whatever else, but I don't know h...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1546] opened 2015-05-12 06:16 UTC
html5 input event support!  it works a lot nicer than keyup or whatever else, but I don&#39;t know how well-supported it is.

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+3__
Issue added by __wulftone__ on __2013-02-25__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment] 2015-05-19 04:51
Duplicate of #1165.

**Closed** 2015-05-22 02:38 UTC
Labels: GM import, Support data suggestion
