### ISSUE TITLE
text-indent

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1427] opened 2015-05-12 06:02 UTC
text-indent

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+4__
Issue added by __Joe__ on __2012-07-04__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment] 2015-05-19 04:14
Duplicate of #1065.

**Closed** 2015-05-19 04:15 UTC
Labels: GM import, Support data suggestion
