### ISSUE TITLE
dns-prefetch -> 

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1167] opened 2015-05-12 04:24 UTC
dns-prefetch -&gt; https://developer.mozilla.org/en-US/docs/Web/HTTP/Controlling_DNS_prefetching

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+8__
Issue added by __oli__ on __2014-08-27__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment] 2015-05-19 04:48
Duplicate of #1072.

**Closed** 2015-05-22 02:48 UTC
Labels: GM import, Support data suggestion

**Comment by kimslawson** [comment] 2015-08-26 19:24
+1
