### ISSUE TITLE
ResizeObserver

### ISSUE THREAD

**Issue by LeaVerou** [Fyrd/caniuse#3298] opened 2017-03-26 03:58 UTC
Supported on Chrome 54+, in development on Firefox

https://www.chromestatus.com/feature/5705346022637568
https://developers.google.com/web/updates/2016/10/resizeobserver
Proposal: https://wicg.github.io/ResizeObserver/

**Comment by Fyrd** [comment] 2017-03-27 03:23
Duplicate of #3006

**Closed by Fyrd** 2017-03-27 03:23 UTC
Labels: Support data suggestion
