### ISSUE TITLE
text-outline

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1500] opened 2015-05-12 06:10 UTC
text-outline

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+3__
Issue added by __Nico__ on __2011-10-23__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment] 2015-05-19 06:05
Duplicate of #1362.

**Closed** 2015-05-22 02:30 UTC
Labels: GM import, Support data suggestion
