### ISSUE TITLE
Add URLSearchParams 

### ISSUE THREAD

**Issue by ghosttie** [Fyrd/caniuse#2275] opened 2016-02-03 00:43 UTC
https://developers.google.com/web/updates/2016/01/urlsearchparams?hl=en

**Comment by cvrebert** [comment] 2016-02-03 02:41
Duplicate of #2213. Try searching next time?

**Comment by ghosttie** [comment] 2016-02-03 03:42
I did, I searched for URLSearchParams  and it came back with no results.  Even now if I do the search it only finds this issue.

**Closed** 2016-02-03 14:38 UTC
