### ISSUE TITLE
Add the ::marker pseudo element

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1179] opened 2015-05-12 04:58 UTC
Add the ::marker pseudo element

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+7__
Issue added by __jd__ on __2014-09-03__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment] 2015-05-19 06:04
Duplicate of #1114.

**Closed** 2015-05-22 02:32 UTC
Labels: GM import, Support data suggestion
