### ISSUE TITLE
CSS Selectors Level 4. I've heard some are being implemented, but the subject of selector unfort...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1384] opened 2015-05-12 05:56 UTC
CSS Selectors Level 4. I&#39;ve heard some are being implemented, but the subject of selector unfortunately has not been (sometimes referred to, but not limited to, as the parent selector).

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+4__
Issue added by __Allen__ on __2013-02-22__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment] 2015-05-19 03:21
Duplicate of #1182.

**Closed** 2015-05-19 03:56 UTC
Labels: GM import, Support data suggestion
