### ISSUE TITLE
Suggestion: export

### ISSUE THREAD

**Issue by stevage** [Fyrd/caniuse#2611] opened 2016-06-27 05:16 UTC
https://developer.mozilla.org/en/docs/web/javascript/reference/statements/export

**Comment by khanh2003** [comment] 2016-06-27 08:57
+1

**Comment by cvrebert** [comment] 2016-06-28 04:47
Duplicate of #1869?

**Comment by dotnetCarpenter** [comment] 2016-10-23 16:52
@stevage @cvrebert yes, its the export part of es6 modules #1869

**Closed** 2019-03-13 05:09 UTC
Labels: Duplicate
