### ISSUE TITLE
Add: model-viewer

### ISSUE THREAD

**Issue by adhesiv** [Fyrd/caniuse#5932] opened 2021-06-04 06:58 UTC
Please add x-support for model-viewer

https://modelviewer.dev/

**Comment by Schweinepriester** [comment] 2021-06-04 08:43
While there is support defined at <https://modelviewer.dev/#section-browser-support> the following ([source](https://github.com/Fyrd/caniuse/issues/5465#issuecomment-640378688))

> Caniuse only tracks browser features, not library/frameworks. Will leave this issue open to add a search result.

applies.

**Comment by Fyrd** [comment] 2021-06-06 04:55
What @Schweinepriester said, and also duplicate of #4915, see more details there.

**Closed by Fyrd** 2021-06-06 04:55 UTC
Labels: Duplicate
