### ISSUE TITLE
OpenSearch support

### ISSUE THREAD

**Issue by neopostmodern** [Fyrd/caniuse#1675] opened 2015-06-20 10:08 UTC
I am a huge fan of searching different sites [straight out of Firefox](https://support.mozilla.org/en-US/kb/use-search-bar-firefox-and-manage-search-engines?redirectlocale=en-US&redirectslug=search-bar-easily-choose-your-search-engine#w_add-a-search-engine) (especially in combination with the customizable keywords).
Unfortunately it's currently unavailable. If I understood [this blog entry](http://davidwalsh.name/open-search) correctly, this is handled by [OpenSearch](http://www.opensearch.org/Home), so all that would be necessary to do is add the XML file.
If someone knows all the values to put in there it would be really fast for them to do, otherwise I can look into it myself and write a PR eventually.

**Comment by Fyrd** [comment] 2015-11-23 04:16
Duplicate of #648

**Closed by Fyrd** 2015-11-23 04:16 UTC
Labels: Site functionality
