### ISSUE TITLE
CSS “attr()” function

### ISSUE THREAD

**Issue by Timwi** [Fyrd/caniuse#1866] opened 2015-08-31 10:47 UTC
It would be nice if caniuse.com could add an element that explains to what extent browsers support the attr() function in CSS. As I understand it, the function should be usable in any CSS property whatsoever, but most browsers only support it in a very limited set of properties.

**Comment by cvrebert** [comment] 2015-08-31 21:28
Duplicate of #1209.

**Closed** 2015-09-02 03:35 UTC
Labels: Duplicate
