### ISSUE TITLE
Waterfox

### ISSUE THREAD

**Issue by a8nJ** [Fyrd/caniuse#5675] opened 2020-10-30 14:22 UTC
Please consider adding this browser:

https://github.com/MrAlex94/Waterfox

as lack of support for this, is causing major sites to break (https://crates.io)

**Comment by Fyrd** [comment] 2020-11-01 04:31
Duplicate of #4666

**Closed by Fyrd** 2020-11-01 04:31 UTC

**Comment by a8nJ** [comment] 2020-11-01 04:34
@Fyrd 

> As with seamonkey, not different enough from Firefox nor enough usage to warrant including.

this comment isnt really true anymore, if it ever was. As mentioned in my original comment, some sites are breaking on Waterfox that work on Firefox, due to said differences.
