### ISSUE TITLE
Lack of IE10 in compare tables

### ISSUE THREAD

**Issue by Konrud** [Fyrd/caniuse#2491] opened 2016-04-30 13:11 UTC
Why there is no IE10 in compare tables, only IE8, IE9 and then IE11 instead of IE10?
 Is this something wrong with support to IE10 as I know its support doesn't match to IE11.

**Comment by Fyrd** [comment] 2016-04-30 18:00
Duplicate of #2436

**Closed by Fyrd** 2016-04-30 18:00 UTC
Labels: Duplicate
