### ISSUE TITLE
Site down

### ISSUE THREAD

**Issue by Bilge** [Fyrd/caniuse#6925] opened 2023-12-21 15:02 UTC
* https://caniuse.com/
* https://downforeveryoneorjustme.com/caniuse.com?proto=https

![image](https://github.com/Fyrd/caniuse/assets/470626/f9bf2d3b-2318-46cc-aea4-1a42f5344ebc)

🤷🏻

**Comment by Fyrd** [comment] 2023-12-21 16:35
Thanks for reporting, yeah there's been some intermittent outages lately, still trying to determine the cause.

**Comment by Fyrd** [comment] 2024-01-02 07:11
Seems to have stabilized now, so closing this ticket.

**Closed by Fyrd** 2024-01-02 07:11 UTC
