### ISSUE TITLE
Array.prototype.find() not listed

### ISSUE THREAD

**Issue by dsegovia90** [Fyrd/caniuse#4261] opened 2018-05-17 03:23 UTC
Hello! First time suggesting something here. First of all nice work, I frequently visit this page for reference!

I stumbled upon a function that is not found when searched, and it's this one: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find

Especially since IE does not support it. 

Cheers, and any feedback on how to better format a request is greatly appreciated!
Daniel S.

**Comment by cpplearner** [comment] 2018-05-17 03:32
duplicate of #1960

**Closed** 2018-05-21 05:53 UTC
Labels: Duplicate

**Comment by Fyrd** [comment] 2018-05-21 05:54
Thanks for the kind words, @dsegovia90 ! As mentioned, this request is already covered by #1960.
