### ISSUE TITLE
Add h.265 (hevc) support

### ISSUE THREAD

**Issue by pszemus** [Fyrd/caniuse#2528] opened 2016-05-25 11:59 UTC

**Comment by Technologov** [comment] 2016-07-24 02:03
+1.
Very useful.
As of today (24.07.2016) -- the only browser that supports HEVC is Chrome for Android, assuming Android 5.x+

**Comment by Fyrd** [comment] 2017-05-26 03:58
Duplicate of #1576, now available at http://caniuse.com/#feat=hevc

**Closed by Fyrd** 2017-05-26 03:58 UTC
Labels: Support data suggestion
