### ISSUE TITLE
add for...of loops

### ISSUE THREAD

**Issue by charsi** [Fyrd/caniuse#4194] opened 2018-04-11 18:24 UTC
Can't see a page for [for...of](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of) loops. 

These are new in ES6. Firefox supported them [early](https://hacks.mozilla.org/2015/04/es6-in-depth-iterators-and-the-for-of-loop/). Would be useful to know which browsers have this feature now.

**Comment by cvrebert** [comment] 2018-04-16 04:51
Duplicate of #4097

**Comment by YakovL** [comment] 2019-03-20 09:17
why not close the duplicate?

**Comment by vojta001** [comment] 2021-11-23 14:54
This is implemented as far as I can tell: https://caniuse.com/?search=for%20of

**Closed** 2021-11-23 19:28 UTC
Labels: Support data suggestion
