### ISSUE TITLE
voice-* properties aren't listed

### ISSUE THREAD

**Issue by caluap** [Fyrd/caniuse#6003] opened 2021-08-30 14:48 UTC
‘voice-family’, ‘voice-rate’, ‘voice-pitch’ etc.

**Comment by Malvoz** [comment] 2022-01-17 15:43
The [Voice characteristic properties](https://drafts.csswg.org/css-speech-1/#voice-char-props) are defined in the CSS Speech Module, as such this issue is duplicate of https://github.com/Fyrd/caniuse/issues/1240.

**Comment by Fyrd** [comment] 2022-10-09 18:00
Closing as per above.

**Closed by Fyrd** 2022-10-09 18:00 UTC
Labels: Support data suggestion, Duplicate
