### ISSUE TITLE
Add background-position-x and background-position-y

### ISSUE THREAD

**Issue by dscafati** [Fyrd/caniuse#2195] opened 2016-01-06 15:06 UTC
These sound very intuitive but don't work in latest firefox versions. I found these are not standard, rather, these where originally implemented by MSIE only

**Comment by cvrebert** [comment] 2016-01-07 07:51
https://drafts.csswg.org/css-backgrounds-4/#background-position-longhands

**Comment by cvrebert** [comment] 2016-01-07 07:56
[Firefox doesn't yet support them.](https://bugzilla.mozilla.org/show_bug.cgi?id=550426)
According to http://snook.ca/archives/html_and_css/background-position-x-y , they work in all the other major browsers, and don't work in Presto.

**Comment by yisibl** [comment] 2016-01-12 10:18
:+1:

**Comment by Fyrd** [comment] 2016-01-14 05:21
Duplicate of #989

**Closed by Fyrd** 2016-01-14 05:21 UTC
Labels: Duplicate
