### ISSUE TITLE
Add HTTP 307 & 308 redirects

### ISSUE THREAD

**Issue by GeorgeBailey** [Fyrd/caniuse#2648] opened 2016-07-14 17:44 UTC
Some background

**HTTP 301 Moved Permanently** is widely support, but converts POST requests to GET, supported since forever
**HTTP 303 See Other** (aka Moved Temporarily) is the 'subject to change' version of 301, supported since IE4
**HTTP 302 Found** is what most people use instead of HTTP 303, but 'technically' 302 was incorrectly implemented, so folks should use 303 instead.

Then there's the new ones.

**HTTP 307 Temporary Redirect** is like 302 or 303 'temporary redirect', except it preserves POST and postdata associated with the request. (isn't that cool!) It was defined in 1999, but I don't know what browsers support it. (IE7+?)
**HTTP 308 Permanent Redirect** also preserves postdata like a 307, but is marked permanent like a 301. Only [introduced in 2012](https://blogs.msdn.microsoft.com/ieinternals/2012/03/29/pushing-the-web-forward-with-http308/) so the browser support for that is going to be sketchy. [see also Wikipedia](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#3xx_Redirection)

Note: Browsers that do not support the given status will display the response body that the server sends. This can be used by developers to a) suggest upgrading the browser, and b) explain that the site has moved.

**Comment by Ugoku** [comment] 2016-07-15 10:14
Duplicate of #1830

**Closed** 2020-06-27 17:44 UTC
Labels: Duplicate, Support data suggestion
