### ISSUE TITLE
String.fromCharCode

### ISSUE THREAD

**Issue by robertjwozniak** [Fyrd/caniuse#4412] opened 2018-07-31 19:43 UTC
I'd be great to add `String.fromCharCode`.  I couldn't find it when I was looking for it.
<a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/fromCharCode"> MDN - String.fromCharCode</a>

**Comment by cpplearner** [comment] 2018-08-01 00:43
-1. It's present in ECMA-262 1st edition and is supported everywhere.

**Comment by cpplearner** [comment] 2018-08-01 00:48
Also, duplicate of #2530 and #3264

**Closed** 2018-08-01 00:50 UTC
