### ISSUE TITLE
I was wondering about whether I should use the <output> element to house output from and input...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1405] opened 2015-05-12 05:59 UTC
I was wondering about whether I should use the &lt;output&gt; element to house output from and input[type=&quot;range&quot;].  But I don&#39;t see an entry for &lt;output&gt;. Here&#39;s the spec: http://dev.w3.org/html5/spec-preview/the-output-element.html

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+4__
Issue added by __kerry__ on __2014-09-19__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment] 2015-05-19 09:09
Duplicate of #1107.

**Closed** 2015-05-20 04:55 UTC
Labels: GM import, Support data suggestion
