### ISSUE TITLE
Attribute autoplay on video tag

### ISSUE THREAD

**Issue by andrewvaca** [Fyrd/caniuse#3140] opened 2017-01-27 10:29 UTC
I would like to see the range of supported mobile browsers for autoplay addtribute of video HTML5 tag. I've found this table, but I's not up to date and and not all browsers:
OS/Browser	Supports autoplay
iOS 9 Safari 601	no
iOS 10 Safari 602	yes (with muted + playsinline attributes)
iOS 9 Chrome 54	no
iOS 10 Chrome 54	yes (with muted + playsinline attributes)
iOS 9 Opera Mini 14	no
iOS 10 Opera Mini 14	yes (plays fullscreen)
iOS 9 Firefox 5.3	no
iOS 10 Firefox 5.3	no
Android Chrome 43	no
Android Chrome 54	yes (with muted attribute)
Android Opera Mini 20	no
Android Firefox 49	yes
Android Samsung Internet 4.0	no
Windows Phone 8 IEMobile 10	no
Windows Phone 8.1 IEMobile 11	yes
Windows 10 Mobile Edge 14.1	no
Windows 10 Mobile Opera Mini 9.1	no
source http://walterebert.com/blog/html5-video-autoplay-mobile-revisited/

**Comment by Schweinepriester** [comment] 2017-01-27 13:55
Duplicate of #2599? The source/link seems relevant, though.

**Closed** 2017-02-02 04:18 UTC
Labels: Duplicate
