### ISSUE TITLE
Add opensearch compatibility to the site. 

### ISSUE THREAD

**Issue by kirilloid** [Fyrd/caniuse#2104] opened 2015-11-23 01:21 UTC
The site is mostly used for single look-up.
I think it would be truly beneficial to automatically register caniuse as a search engine which is accessible directly from omnibox in (at least) Chrome and Firefox: http://stackoverflow.com/a/32687089/255363

**Comment by Fyrd** [comment] 2015-11-23 04:17
Duplicate of #648

**Closed by Fyrd** 2015-11-23 04:17 UTC
