### ISSUE TITLE
It would be helpful to have support for the state of paged media ( @page )

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1302] opened 2015-05-12 05:13 UTC
It would be helpful to have support for the state of paged media ( @page )

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+5__
Issue added by __Marco__ on __2014-04-04__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment] 2015-05-19 07:33
Duplicate of #1229

**Closed** 2015-05-20 03:27 UTC
Labels: GM import, Support data suggestion
