### ISSUE TITLE
Microsoft Connect is dead

### ISSUE THREAD

**Issue by mkurz** [Fyrd/caniuse#4067] opened 2018-02-07 12:42 UTC
Look at this: https://docs.microsoft.com/en-us/collaborate/connect-redirect

I did a quick `grep` and there are 18 unique MS Connect links left which point to a dead end.
Some of them may be still available in the [Google cache](http://webcache.googleusercontent.com/search?q=cache:) (using `cache:<url>`), some could maybe "restored" via http://web.archive.org/. Or at least these pages would help us to find out where they have been redirect to in MS new bug database - which is  https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/. However I think not all of the bugs have been copied over to the new bug database...

**So, these bugs are effected which still show up in the caniuse repo**:
(Note: Some of these url's actually don't show up like this in the caniuse repo, some have a different prefix like `.../IE/feedbackdetail/view/...` or have a text added the the path like `.../885747/ie-11-fires-the-input-event-when-a-input-field-with-placeholder-is-focused`. So if someone tries to restore these links e.g. with Google cache or webarchive maybe these original urls are used for these cached pages, not the urls below):

https://connect.microsoft.com/IE/feedback/details/1847897
https://connect.microsoft.com/IE/feedback/details/1883692
https://connect.microsoft.com/IE/feedback/details/759587
https://connect.microsoft.com/IE/feedback/details/762719
https://connect.microsoft.com/IE/feedback/details/776744 (twice)
https://connect.microsoft.com/IE/feedback/details/781303
https://connect.microsoft.com/IE/feedback/details/795172
https://connect.microsoft.com/IE/feedback/details/800076
https://connect.microsoft.com/IE/feedback/details/802625
https://connect.microsoft.com/IE/feedback/details/816293
https://connect.microsoft.com/IE/feedback/details/817132
https://connect.microsoft.com/IE/feedback/details/817488
https://connect.microsoft.com/IE/feedback/details/828416
https://connect.microsoft.com/IE/feedback/details/829392
https://connect.microsoft.com/IE/feedback/details/885747 (twice)
https://connect.microsoft.com/IE/feedback/details/920928
https://connect.microsoft.com/IE/feedback/details/926665
https://connect.microsoft.com/IE/feedback/details/962368
~~https://connect.microsoft.com/IE/feedback/details/811408~~ (twice) (fixed in #4066 already)

**Comment by Fyrd** [comment] 2018-02-09 06:01
Ugh.

**Comment by Fyrd** [comment] 2018-02-09 06:06
@mkurz Thanks for the research and getting that list of URLs.

@dstorey Any recommendations on how to deal with this? Do all the old connect bug IDs map to urls in the new database by any chance?

**Comment by dstorey** [comment] 2018-02-09 20:59
They should do I believe. Adding @molant

**Comment by molant** [comment] 2018-02-12 17:35
> Do all the old connect bug IDs map to urls in the new database by any chance?

Unfortunately they don't map. For each issue there should have been a link in the comments to the new issue tracker with the new id. 

> However I think not all of the bugs have been copied over to the new bug database...

If some aren't the most common scenarios are:

* they were linked to a feature and not a bug
* they were marked as dupes of another one

**Comment by mkurz** [comment] 2018-02-12 17:46
@molant Do you still have access somehow to the now offline MS Connect database (or one of it's backups)? It would be great if we somehow could update the dead links...

**Comment by molant** [comment] 2018-02-13 17:34
@mkurz I'm looking into it, although I can't make any promises.

I'll keep you posted!

**Comment by mkurz** [comment] 2018-02-13 17:35
@molant Thank you very much! :smile:

**Comment by molant** [comment] 2018-02-14 17:27
@mkurz do you know if those issues are still open or closed? I have found more than 1000+ items from the old system and that would help me narrow a lot the search (can't use the old ids to search them 😞)

**Comment by mkurz** [comment] 2018-02-14 17:33
@molant Sorry, I don't know. I would guess some are open and some are already closed...
Interesting, why can't you search by id? I'd imagine the id was used as a primary key for the issues in an relational database... Or not? Do you have access to the db or just some frontend?

**Comment by molant** [comment] 2018-02-14 17:59
@mkurz connect was a separate system than the one used by the engineers. There were some bots doing the syncing from one place to another. 
The only place where I've found the connect's ID in the engineering system is in the first comment of the bot. Unfortunately comments aren't indexed 😞
You can't imagine how happy we were when we stopped using connect.

Going back to the subject, I'll probably have to write a script to do this so it will take longer than expected while I find some time to do it.

**Comment by mkurz** [comment] 2018-02-14 18:06
Alright, I understand :smile:
Can you not just simply somehow switch on that old frontend that's offline now - or is it completely gone? (I know I know it's not easy... :wink: )
Anyway, thanks a ton for your efforts!

**Comment by molant** [comment] 2018-03-05 23:44
Here goes the list with all the bugs I could find. Not sure where I can find the missing ones though 😞

| Old url | New ulr |
|---------|----------|
| https://connect.microsoft.com/IE/feedback/details/1847897 | Not found |
| https://connect.microsoft.com/IE/feedback/details/1883692 | Not found |
| https://connect.microsoft.com/IE/feedback/details/759587 | Not found |
| https://connect.microsoft.com/IE/feedback/details/762719 | Not found |
| https://connect.microsoft.com/IE/feedback/details/776744 | https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/250661/ |
| https://connect.microsoft.com/IE/feedback/details/781303 | Not found |
| https://connect.microsoft.com/IE/feedback/details/795172 | Not found |
| https://connect.microsoft.com/IE/feedback/details/800076 | Not found |
| https://connect.microsoft.com/IE/feedback/details/802625 | Not found |
| https://connect.microsoft.com/IE/feedback/details/816293 | Not found |
| https://connect.microsoft.com/IE/feedback/details/817132 | Not found |
| https://connect.microsoft.com/IE/feedback/details/817488 | Not found |
| https://connect.microsoft.com/IE/feedback/details/828416 | Not found |
| https://connect.microsoft.com/IE/feedback/details/829392 | Not found |
| https://connect.microsoft.com/IE/feedback/details/885747 | https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/274987/ |
| https://connect.microsoft.com/IE/feedback/details/920928 | https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/650529/ |
| https://connect.microsoft.com/IE/feedback/details/926665 | https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/640805/ |
| https://connect.microsoft.com/IE/feedback/details/962368 | https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/798766/ |

**Comment by Fyrd** [comment] 2020-05-01 03:30
There's no more MS Connect URLs on the site, so closing this issue.

**Closed by Fyrd** 2020-05-01 03:30 UTC
Labels: Misc. site/data request
