### ISSUE TITLE
http://www.w3.org/TR/css3-marquee/ is not searchable here in Caniuse.

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1258] opened 2015-05-12 05:08 UTC
http://www.w3.org/TR/css3-marquee/ is not searchable here in Caniuse.

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+6__
Issue added by __TylerH__ on __2014-09-30__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment] 2015-05-19 07:11
Duplicate of #1499.

**Closed** 2015-05-20 03:16 UTC
Labels: GM import, Support data suggestion
