### ISSUE TITLE
Add the (view-mode) media feature

### ISSUE THREAD

**Issue by tabatkins** [Fyrd/caniuse#2427] opened 2016-04-13 14:46 UTC
Defined in https://www.w3.org/TR/view-mode/

**Comment by GustvandeWal** [comment] 2020-02-10 20:49
Duplicate of https://github.com/Fyrd/caniuse/issues/2518

**Comment by Fyrd** [comment] 2020-03-27 03:33
Available at https://caniuse.com/#feat=mdn-css_at-rules_media_display-mode

**Closed by Fyrd** 2020-03-27 03:33 UTC
Labels: Support data suggestion
