### ISSUE TITLE
maxlength attribute for <input> and <textarea>

### ISSUE THREAD

**Issue by ramiy** [Fyrd/caniuse#1770] opened 2015-07-30 16:01 UTC
The maxlength attribute limits the number of characters that an *input* or *textarea* can accept.

More info:

* http://www.w3schools.com/tags/att_input_maxlength.asp
* http://www.w3schools.com/tags/att_textarea_maxlength.asp
* http://www.wufoo.com/html5/attributes/03-maxlength.html

**Comment by cvrebert** [comment] 2015-07-31 10:08
+1

**Comment by Serabe** [comment] 2015-08-18 18:24
+1 Specially given iOS 8 buggy support for it

**Comment by cvrebert** [comment] 2015-09-10 09:45
Duplicate of #1106.

**Comment by cvrebert** [comment] 2015-09-15 02:07
@Fyrd This can be closed as a duplicate.

**Comment by cvrebert** [comment] 2015-09-15 02:10
@Serabe I didn't notice any bugs when I was testing it: https://github.com/Fyrd/caniuse/blob/0000fee647ba9d2a8f9d6b75a1b96a8ec8509f0b/features-json/maxlength.json#L178-L179

**Closed** 2015-09-15 03:11 UTC
Labels: Duplicate, Support data suggestion

**Comment by Serabe** [comment] 2015-09-15 09:13
@cvrebert in an iOS device type into the field the max number of characters. Then, move the cursor to the middle of the input and continue typing. You should see that the characters you type are being inserted.

**Comment by cvrebert** [comment] 2015-09-15 20:12
@Serabe Thanks for the info! I was able to confirm the bug. Looks like it applies to `<input>`s on iOS 8.0-8.4 and has been fixed in iOS 9.0. Safari won't let the user add extra characters at the start or end of a maxlength string, but it does allow them to add extra characters to the interior of the string.
I'll open a pull request to add this info.
