### ISSUE TITLE
img@crossorigin (see  and perhaps 

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1476] opened 2015-05-12 06:07 UTC
img@crossorigin (see https://developer.mozilla.org/en/CORS_Enabled_Image#Browser_compatibility) and perhaps http://h5bp.com/i/797

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+3__
Issue added by __Mathias Bynens__ on __2011-12-05__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment] 2015-05-20 06:11
Duplicate of #1396.

**Closed** 2015-05-21 03:53 UTC
Labels: GM import, Support data suggestion
