### ISSUE TITLE
Meta referrer  -  - 

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1154] opened 2015-05-12 04:23 UTC
Meta referrer: http://wiki.whatwg.org/wiki/Meta_referrer

- https://code.google.com/p/chromium/issues/detail?id=105028
- https://bugzilla.mozilla.org/show_bug.cgi?id=704320

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+8__
Issue added by __Brandon Frohs__ on __2014-09-09__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment] 2015-05-19 07:46
Duplicate of #1214.

**Closed** 2015-05-20 04:35 UTC
Labels: GM import, Support data suggestion
