### ISSUE TITLE
Implement CSSOM offsetParent Property

### ISSUE THREAD

**Issue by jabcreations** [Fyrd/caniuse#3645] opened 2017-08-06 21:52 UTC
The offsetParent is useful for determining if the element in question is visible which is a critical prerequisite to determine before giving that element focus.

Mozilla Developer Network:
https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/offsetParent

Standards Definition:
https://drafts.csswg.org/cssom-view/#dom-htmlelement-offsetparent

Blink:
https://bugs.chromium.org/p/chromium/issues/detail?id=242166

Gecko Bug (no implementation bug for Gecko found):
https://bugzilla.mozilla.org/show_bug.cgi?id=434678

WebKit:
https://bugs.webkit.org/show_bug.cgi?id=113276

**Comment by Schweinepriester** [comment] 2017-08-07 08:57
Though this ticket has a way better description, I'm afraid it's a duplicate of #1846, which already has 8 votes.

If duplicate, maybe post this as comment there? :)

**Comment by Fyrd** [comment] 2017-08-09 03:56
Agreed, good information there! But it is a dupe.

**Closed by Fyrd** 2017-08-09 03:56 UTC
Labels: Duplicate

**Comment by jabcreations** [comment] 2017-08-09 04:05
Here is a crazy idea: mark totally crap posts as dupes of quality posts. By copying Mozilla's terrible bug handling you're only discouraging quality posters.

**Comment by Fyrd** [comment] 2017-08-09 05:53
I don't think caniuse feature requests need to meet the same quality standards as Mozilla bugs. As long as the information's there it doesn't seem like it matters much. Also I don't have a way of transferring votes from one issue to another, so...
