### ISSUE TITLE
when.caniuse this?

### ISSUE THREAD

**Issue by bitdivine** [Fyrd/caniuse#2419] opened 2016-04-09 18:26 UTC
Hello,

Does caniuse have a notification system so that you can let me know when support for a feature reaches a certain level?  You could host such a service under "https://when.caniuse.com" and have a subscription button on each page. :-)

If not I'd be happy to make this, if you like!

Today I'd love to subscribe to css variables.  When IE gets round to supporting it I'd like to use them, but I don't have a hook to bring me back to your page as soon as the situation changes.  Absent minded mathematicians are forgetful y'know.

Many thanks for a great site.

Regards, Max

**Comment by cvrebert** [comment] 2016-04-10 06:33
Approximate duplicate of #869?

**Comment by bitdivine** [comment] 2016-04-11 17:28
Yes, looks like it.  Sorry for not finding the original. If it hasn't been built, are you OK with my making an e-mail or web-push implementation?

**Comment by Fyrd** [comment] 2016-04-13 03:47
Someone made this about a year ago, sadly it's not running anymore:
https://web.archive.org/web/20150425094432/http://frontendhq.com/pinger

You're welcome to make a 3rd party service like this, absolutely. No plans to do it myself though.

**Comment by Fyrd** [comment] 2020-05-01 03:39
Closing in favor of #869

**Closed by Fyrd** 2020-05-01 03:39 UTC
Labels: Duplicate, Misc. site/data request
