### ISSUE TITLE
X-Frame-Options header

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1433] opened 2015-05-12 06:02 UTC
X-Frame-Options header

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+4__
Issue added by __Kevin__ on __2012-11-07__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment] 2015-05-19 04:16
Duplicate of #1138.

**Closed** 2015-05-19 04:16 UTC
Labels: GM import, Support data suggestion
