### ISSUE TITLE
maxlength for textarea

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1321] opened 2015-05-12 05:15 UTC
maxlength for textarea

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+5__
Issue added by __Dael__ on __2012-02-24__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment] 2015-09-10 09:46
Duplicate of #1106.

**Comment by cvrebert** [comment] 2015-09-15 02:10
@Fyrd This can be closed as a duplicate.

**Closed** 2015-09-15 03:09 UTC
Labels: Duplicate, GM import, Support data suggestion
