### ISSUE TITLE
dynamic import()

### ISSUE THREAD

**Issue by Lonniebiz** [Fyrd/caniuse#4265] opened 2018-05-19 09:33 UTC
Please add [dynamic import()](https://developers.google.com/web/updates/2017/11/dynamic-import).

I went to caniuse to see when dynamic import would also be supported in firefox, but I see no mention of it.

**Comment by Fyrd** [comment] 2018-05-21 05:58
Duplicate of #3901

**Closed by Fyrd** 2018-05-21 05:58 UTC
