### ISSUE TITLE
http://dev.w3.org/csswg/mediaqueries-4/

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1315] opened 2015-05-12 05:15 UTC
http://dev.w3.org/csswg/mediaqueries-4/

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+5__
Issue added by __fbtb__ on __2015-04-20__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment] 2015-05-19 03:11
@Fyrd Duplicate of #1069.

**Closed** 2015-05-19 03:52 UTC
Labels: GM import, Support data suggestion
