### ISSUE TITLE
Add Subresource Integrity

### ISSUE THREAD

**Issue by Gaff** [Fyrd/caniuse#1881] opened 2015-09-02 17:54 UTC
It has a w3c page and it's in some versions of Chrome apparently: https://w3c.github.io/webappsec/specs/subresourceintegrity/

**Comment by xtian** [comment] 2015-09-07 14:33
+1

**Comment by cvrebert** [comment] 2015-09-15 02:11
+

**Comment by mxstbr** [comment] 2015-09-19 07:33
+1

**Comment by qgy18** [comment] 2015-09-23 00:53
+1

**Comment by okor** [comment] 2015-09-24 21:34
+1

**Comment by snadrus** [comment] 2015-09-24 22:52
+ 1
From HTML5 Weekly:
GitHub Enables Subresource Integrity for CDN Assets NEWS 
Uses a new browser technology called Subresource Integrity.  
GITHUB ENGINEERING

**Comment by yukulele** [comment] 2015-09-26 11:26
+1

**Comment by yukulele** [comment] 2015-09-26 11:27
Article on Mozilla Hacks: https://hacks.mozilla.org/2015/09/subresource-integrity-in-firefox-43/

**Comment by yukulele** [comment] 2015-09-26 11:32
you can test it on your browser here:
https://srihash.org/

**Comment by connorshea** [comment] 2015-09-27 14:30
+1

**Comment by connorshea** [comment] 2015-09-27 14:30
[GitHub uses it](http://githubengineering.com/subresource-integrity/).

**Comment by brendanheywood** [comment] 2015-09-30 23:10
+1

**Comment by arianitu** [comment] 2015-10-01 15:37
:+1:

**Comment by arianitu** [comment] 2015-10-01 15:37
+1

**Comment by vermorel** [comment] 2015-10-01 21:09
+1

**Comment by jpmedley** [comment] 2015-10-02 16:40
+1

**Comment by samarpanda** [comment] 2015-10-04 01:37
:+1:

**Comment by M2Ys4U** [comment] 2015-10-06 19:48
+1

**Comment by paulirish** [comment] 2015-10-07 23:15
support right now… 

* [FF 43+](https://hacks.mozilla.org/2015/09/subresource-integrity-in-firefox-43/)
* [Chrome 45+](https://www.chromestatus.com/features/6183089948590080) (and Opera 32+)

**Comment by yukulele** [comment] 2015-10-10 03:12
https://github.com/Fyrd/caniuse/issues/1170

**Comment by MattiSG** [comment] 2015-10-10 08:35
+1

Duplicate of #1170.

**Comment by thekondrashov** [comment] 2015-10-10 16:50
+1

**Comment by Schweinepriester** [comment] 2015-10-16 15:13
> Duplicate of #1170.

+1

**Comment by cvrebert** [comment] 2015-10-23 07:37
https://dev.modern.ie/platform/status/subresourceintegrity/

**Comment by ApfelUser** [comment] 2015-10-23 15:46
+1

**Comment by sandstrom** [comment] 2015-10-26 21:30
+1

**Comment by Naddiseo** [comment] 2015-10-28 16:04
+1

**Comment by Mictian** [comment] 2015-10-29 23:21
+1

**Comment by branneman** [comment] 2015-10-30 10:07
+1

**Comment by Fyrd** [comment] 2015-11-03 06:49
Now available at http://caniuse.com/#feat=subresource-integrity

**Closed by Fyrd** 2015-11-03 06:49 UTC
Labels: Support data suggestion

**Comment by Gaff** [comment] 2015-11-28 19:19
Yay - thanks!
