### ISSUE TITLE
View Transitions API

### ISSUE THREAD

**Issue by nathanbabcock** [Fyrd/caniuse#6646] opened 2023-03-12 19:23 UTC
Supported by default in latest version of Chrome, in progress on Edge & Opera. I'm beginning to see some articles about it this week.

https://developer.mozilla.org/en-US/docs/Web/API/View_Transitions_API

https://www.w3.org/TR/css-view-transitions-1/

**Comment by Schweinepriester** [comment] 2023-03-13 12:30
(Technically duplicate of https://github.com/Fyrd/caniuse/issues/6461, but since you created a PR only linking it with this comment 0:-))

**Comment by nathanbabcock** [comment] 2023-03-13 12:58
Whoopsies, didn't search under that name 😅

**Comment by Fyrd** [comment] 2023-06-12 06:18
Now available at https://caniuse.com/view-transitions

**Closed by Fyrd** 2023-06-12 06:18 UTC
Labels: Support data suggestion
