### ISSUE TITLE
zoom - css property

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1285] opened 2015-05-12 05:11 UTC
zoom - css property

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+5__
Issue added by __Edgaras__ on __2012-11-06__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment] 2015-05-19 06:15
-1

**Comment by pkuczynski** [comment] 2015-06-26 10:02
This is a duplicate of #1453 and it can be closed @Fyrd

**Closed** 2015-07-06 04:43 UTC
Labels: GM import, Support data suggestion
