### ISSUE TITLE
display:inline-table

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1095] opened 2015-05-12 04:18 UTC
display:inline-table

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+11__
Issue added by __erspark__ on __2014-03-30__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment] 2015-05-19 06:27
Duplicate of #1087.

**Closed** 2015-05-22 02:49 UTC
Labels: GM import, Support data suggestion
