### ISSUE TITLE
Please add Progressive web app manifest.

### ISSUE THREAD

**Issue by SteveALee** [Fyrd/caniuse#2507] opened 2016-05-10 14:53 UTC

**Comment by cvrebert** [comment] 2016-07-22 23:24
Duplicate of #1532?

**Comment by armujahid** [comment] 2018-07-02 09:20
This issue can be closed since #1532 is closed

**Comment by Malvoz** [comment] 2018-11-19 14:07
@Fyrd wanna close this?

**Closed** 2019-03-27 04:37 UTC
Labels: Duplicate, Support data suggestion
