### ISSUE TITLE
DOMAttrModified

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1264] opened 2015-05-12 05:08 UTC
DOMAttrModified

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+6__
Issue added by __Ramon__ on __2014-09-09__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment] 2015-05-19 06:16
Duplicate of #1074.

**Closed** 2015-05-20 04:41 UTC
Labels: GM import, Support data suggestion
