### ISSUE TITLE
Add CSS Color Level 4 new rgb and rgba syntax

### ISSUE THREAD

**Issue by daytonlowell** [Fyrd/caniuse#4732] opened 2019-01-23 22:03 UTC
Chrome, Firefox, & now Safari Technology Preview support it.

The differences are:

There is a new comma-free syntax, where the optional alpha is separated by a slash:
rgb(128 34 56)
rgb(128 34 56 / 50%)

Floating point values are allowed, and rounded:
rgb(128.5 34.2 56.5) becomes rgb(129 34 57)

rgba() is a pure alias for rgb(), so these are equivalent:
rgb(128 34 56 / 50%)
rgba(128 34 56 / 50%)

webkit bug: https://bugs.webkit.org/show_bug.cgi?id=192321

**Comment by felixdivo** [comment] 2019-03-05 11:11
As well as `lab()`/`lch()`/... from [this Editor’s Draft](https://drafts.csswg.org/css-color/#specifying-lab-lch) maybe?

**Comment by Ugoku** [comment] 2019-11-22 09:24
Browser issues  for `lab/lch` support:
* Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=1026287
* Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1352757

**Comment by Schweinepriester** [comment] 2020-01-20 14:24
+1

Syntax with 4th parameter also spec'd for HSL: `hsl(0 0% 0% / 20%);` 🎉 

- <https://www.w3.org/TR/css-color-4/#the-hsl-notation>
- <https://twitter.com/argyleink/status/1218305696862588928>

**Comment by mathiasbynens** [comment] 2020-04-21 11:27
Duplicate of #2679

**Closed** 2020-05-25 06:13 UTC
Labels: Duplicate, Support data suggestion
