### ISSUE TITLE
Text-wrap: balance not available. 

### ISSUE THREAD

**Issue by MarkSmit** [Fyrd/caniuse#6714] opened 2023-05-20 07:24 UTC
The new CSS property `text-wrap: balance` is not available on caniuse.com.
See more information about it [here](https://developer.chrome.com/blog/css-text-wrap-balance/).

**Comment by Schweinepriester** [comment] 2023-05-20 08:42
Excited as well, but this is a duplicate of https://github.com/Fyrd/caniuse/issues/1064.

**Closed** 2023-05-30 05:22 UTC
Labels: Duplicate
