### ISSUE TITLE
Payment Request API

### ISSUE THREAD

**Issue by GregMartyn** [Fyrd/caniuse#2775] opened 2016-09-01 21:55 UTC
This specification describes a web API to allow merchants (i.e. web sites selling physical or digital goods) to easily accept payments from different payment methods with minimal integration. User agents (e.g., browsers) will facilitate the payment flow between merchant and user.

https://www.w3.org/TR/payment-request/

Chrome 53 for Android (desktop to be supported in the future) introduces a new API called Payment Request - a new approach for developers to eliminate checkout forms and improve user’s payment experience from the ground up.

https://developers.google.com/web/updates/2016/07/payment-request?hl=en

**Comment by Ugoku** [comment] 2016-09-02 09:45
Duplicate of #2647

**Closed** 2016-09-17 06:55 UTC
Labels: Duplicate
