### ISSUE TITLE
DOM Mutation Events

### ISSUE THREAD

**Issue by RayFoss** [Fyrd/caniuse#2733] opened 2016-08-17 12:11 UTC
https://developer.mozilla.org/en-US/docs/Web/Events/DOMSubtreeModified

Would love to have some data on this.
```
DOMSubtreeModified	(none)	Fires when the subtree is modified	Yes	No
DOMNodeInserted	(none)	Fires when a node has been added as a child of another node	Yes	No
DOMNodeRemoved	(none)	Fires when a node has been removed from a DOM-tree	Yes	No
DOMNodeRemovedFromDocument	(none)	Fires when a node is being removed from a document	No	No
DOMNodeInsertedIntoDocument	(none)	Fires when a node is being inserted into a document	No	No
DOMAttrModified	(none)	Fires when an attribute has been modified	Yes	No
DOMCharacterDataModified	(none)	Fires when the character data has been modified	Yes	No
```

**Comment by Fyrd** [comment] 2016-08-18 04:15
Duplicate of #1074

**Closed by Fyrd** 2016-08-18 04:15 UTC
