### ISSUE TITLE
add support details for DOMSubtreeModified

### ISSUE THREAD

**Issue by Emanuele-Spatola** [Fyrd/caniuse#2202] opened 2016-01-11 15:06 UTC
https://developer.mozilla.org/en-US/docs/Web/Events/DOMSubtreeModified
http://help.dottoro.com/ljrmcldi.php

**Comment by cvrebert** [comment] 2016-01-12 12:34
Duplicate of #1184. Try searching next time.

**Closed** 2016-01-14 05:15 UTC
Labels: Duplicate
