### ISSUE TITLE
CSS3 background position, 

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1498] opened 2015-05-12 06:10 UTC
CSS3 background position, http://www.w3.org/TR/css3-background/#the-background-position

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+3__
Issue added by __Guy__ on __2013-05-20__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment] 2015-05-19 03:47
Duplicate of #1028.

**Closed** 2015-05-19 03:50 UTC
Labels: GM import, Support data suggestion
