### ISSUE TITLE
window.visualViewport

### ISSUE THREAD

**Issue by mattrummler** [Fyrd/caniuse#4312] opened 2018-06-15 18:09 UTC
I recommend showing the current adoption rate for this feature which is described here on MDN: https://developer.mozilla.org/en-US/docs/Web/API/VisualViewport

Thanks for caniuse it's great!

**Comment by cvrebert** [comment] 2018-06-26 05:35
Duplicate of #3638

**Closed** 2020-05-16 04:50 UTC
Labels: Duplicate, Support data suggestion
