### ISSUE TITLE
any ETA on when svgz will be added? Cheers.

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1294] opened 2015-05-12 05:12 UTC
any ETA on when svgz will be added? Cheers.

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+5__
Issue added by __Steel Brain__ on __2014-08-03__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment] 2015-05-19 08:11
Duplicate of #1180.

**Closed** 2015-05-20 04:46 UTC
Labels: GM import, Support data suggestion
