### ISSUE TITLE
font-display Support

### ISSUE THREAD

**Issue by malchata** [Fyrd/caniuse#2730] opened 2016-08-16 18:10 UTC
I think it'd be a good idea to track support for the CSS `font-display` property in browsers:
https://tabatkins.github.io/specs/css-font-display/

Currently in Chrome 52 or later, the `font-display` is available as a part of Chrome's experimental web platform features.

**Comment by Fyrd** [comment] 2016-08-17 05:56
Duplicate of #2001

**Closed by Fyrd** 2016-08-17 05:56 UTC
