### ISSUE TITLE
Please add insertAdjacentHTML

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1305] opened 2015-05-12 05:13 UTC
Please add insertAdjacentHTML

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+5__
Issue added by __shcoder.ru__ on __2014-09-07__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment] 2015-05-19 03:18
Duplicate of #1044.

**Closed** 2015-05-19 03:56 UTC
Labels: GM import, Support data suggestion
