### ISSUE TITLE
Add statistics for FileSaver API

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1232] opened 2015-05-12 05:05 UTC
Add statistics for FileSaver API

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+6__
Issue added by __Piranna__ on __2012-08-21__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment] 2015-05-19 08:54
Duplicate of #1393.

**Closed** 2015-05-20 04:52 UTC
Labels: GM import, Support data suggestion
