### ISSUE TITLE
H.266/VVC

### ISSUE THREAD

**Issue by kiding** [Fyrd/caniuse#5521] opened 2020-07-07 01:24 UTC
Fraunhofer HHI [announced H.266/VVC.](https://newsletter.fraunhofer.de/-viewonline2/17386/465/11/14SHcBTt/V44RELLZBp/1) Making an issue to track the support status in the (quite far?) future.

**Comment by Schweinepriester** [comment] 2020-07-08 01:02
Duplicate of #5065.

**Closed** 2020-07-08 01:16 UTC
