### ISSUE TITLE
DASH live streaming

### ISSUE THREAD

**Issue by jimmywarting** [Fyrd/caniuse#3046] opened 2016-12-10 13:43 UTC
I see you brought up [HLS](http://caniuse.com/#search=hls) that was invented by Apple but not the DASH format which is a standard. Support will grow over time, so supporting DASH will grow easier over time

https://developer.mozilla.org/en-US/Apps/Fundamentals/Audio_and_video_delivery/Live_streaming_web_audio_and_video#Streaming_File_Format_Support

**Comment by Fyrd** [comment] 2016-12-11 05:06
Duplicate of #1278

**Closed by Fyrd** 2016-12-11 05:06 UTC
