### ISSUE TITLE
woff table missing IE10

### ISSUE THREAD

**Issue by kitsunde** [Fyrd/caniuse#2497] opened 2016-05-06 00:36 UTC
http://caniuse.com/#feat=woff

**Comment by lowbatteries** [comment] 2016-05-06 21:00
It isn't missing, IE10 just isn't shown by default. Click "show all" to see it.

**Comment by Fyrd** [comment] 2016-05-07 18:09
Yup, duplicate of #2436

**Closed by Fyrd** 2016-05-07 18:09 UTC
Labels: Duplicate
