### ISSUE TITLE
insertAdjacentHTML 

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1093] opened 2015-05-12 04:18 UTC
insertAdjacentHTML
https://developer.mozilla.org/en/DOM/Element.insertAdjacentHTML

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+11__
Issue added by __Ramy__ on __2011-11-08__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment] 2015-05-19 03:18
Duplicate of #1044.

**Closed** 2015-05-19 03:55 UTC
Labels: GM import, Support data suggestion
