### ISSUE TITLE
Add CSS Toggle Feature

### ISSUE THREAD

**Issue by yasgo** [Fyrd/caniuse#6582] opened 2023-01-24 11:50 UTC
Hi,

Can you add CSS toggle feature?

**Docs:** https://tabatkins.github.io/css-toggle/
**Example:** https://codepen.io/bramus/pen/dyJaZGp

**Comment by Schweinepriester** [comment] 2023-01-24 13:54
While I'm excited as well, this is a duplicate of https://github.com/Fyrd/caniuse/issues/6250.

**Closed** 2023-01-24 17:22 UTC
