### ISSUE TITLE
CSS paged media  Wikipedia (paged media section) IE

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1122] opened 2015-05-12 04:20 UTC
CSS paged media

Wikipedia: https://en.wikipedia.org/wiki/Comparison_of_layout_engines_(Cascading_Style_Sheets)#Properties (paged media section)
IE: http://msdn.microsoft.com/en-us/library/cc351024(v=VS.85).aspx#printing

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+9__
Issue added by __Mark__ on __2011-10-11__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment] 2015-05-19 07:33
Duplicate of #1229

**Closed** 2015-05-20 03:26 UTC
Labels: GM import, Support data suggestion
