### ISSUE TITLE
WebNFC Support

### ISSUE THREAD

**Issue by ClintonGallagher** [Fyrd/caniuse#3482] opened 2017-06-02 15:50 UTC
W3C is working on a Web NFC API https://w3c.github.io/web-nfc/. Because Web NFC is browser dependent the progress and support should be available at caniuse.com Can we get community support for Web NFC?

Near Field Communication (NFC) enables wireless communication between two devices at close proximity, usually less than a few centimeters. NFC is an international standard (ISO/IEC 18092) defining an interface and protocol for simple wireless interconnection of closely coupled devices operating at 13.56 MHz (see https://www.nfc-forum.org/specs/spec_list/).

**Comment by NOtherDev** [comment] 2017-06-06 20:41
Duplicate of #2085.

**Closed** 2017-06-07 04:36 UTC
Labels: Duplicate
