### ISSUE TITLE
Add data for imageSmoothingEnabled Property (Canvas-related)

### ISSUE THREAD

**Issue by kirupa** [Fyrd/caniuse#2117] opened 2015-11-28 20:35 UTC
More details here: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/imageSmoothingEnabled

:-)

**Comment by tripu** [comment] 2017-09-12 07:47
(Duplicate of #1423. Remove?)

**Comment by tripu** [comment] 2018-04-09 06:58
@Fyrd (ping :) isn't this a duplicate?

**Comment by Fyrd** [comment] 2020-05-06 03:30
Yes, yes it is.

**Closed by Fyrd** 2020-05-06 03:30 UTC
Labels: Duplicate, Support data suggestion
