### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by mimi357** [Fyrd/caniuse#2079] opened 2015-11-10 14:23 UTC
Why not add hex and rgba colour check functionality. By the way I love your work !

**Comment by Ugoku** [comment] 2015-11-19 13:00
[rgba is on caniuse already](http://caniuse.com/#search=rgba)

**Comment by iant-tui** [comment] 2016-07-05 10:20
I suggest this should be closed as a duplicate of #2249, since that covers the half of this that hasn't already been done and has received more attention.

**Closed** 2016-10-08 22:38 UTC
Labels: Duplicate, Support data suggestion
