### ISSUE TITLE
Bindings - Lexical Declarations (const, let)

### ISSUE THREAD

**Issue by Webysther** [Fyrd/caniuse#1635] opened 2015-06-04 23:22 UTC
https://www.chromestatus.com/features/4645595339816960
https://people.mozilla.org/~jorendorff/es6-draft.html#sec-let-and-const-declarations
https://googlechrome.github.io/samples/lexical-declarations-es6/index.html

**Comment by cvrebert** [comment] 2015-06-05 08:35
Approximate duplicate of #1493.

**Comment by Webysther** [comment] 2015-06-05 08:50
yes, only the naming isnt correct. :-)

**Comment by Fyrd** [comment] 2015-06-06 06:21
Alright, added `const` to #1493 and closing this.

**Closed by Fyrd** 2015-06-06 06:21 UTC
