### ISSUE TITLE
window.location.origin

### ISSUE THREAD

**Issue by davidgoli** [Fyrd/caniuse#1815] opened 2015-08-17 23:20 UTC
The best documentation appears on the MDN website https://developer.mozilla.org/en-US/docs/Web/API/URLUtils/origin

Their compatibility charts list Chrome, Firefox, IE, and Safari as all supporting it, but their mobile browser data is missing.

**Comment by cvrebert** [comment] 2015-08-17 23:49
Duplicate of #1803.

**Closed** 2015-08-18 03:56 UTC
Labels: Duplicate
