### ISSUE TITLE
ES6 Template Strings / Template Literals

### ISSUE THREAD

**Issue by a-r-d** [Fyrd/caniuse#2193] opened 2016-01-04 21:41 UTC
Can we add ES6 template literals to caniuse? It is now supported in latest chrome and firefox but not IE. I think this feature may also be called multiline strings in some places. 

MDN Doc:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/template_strings

Spec:
http://www.ecma-international.org/ecma-262/6.0/#sec-template-literals

**Comment by ScratchOs** [comment] 2016-01-06 17:35
+1

**Comment by cvrebert** [comment] 2016-01-07 07:58
https://kangax.github.io/compat-table/es6/#test-template_strings

**Comment by jogibear9988** [comment] 2016-02-11 09:14
+1

**Comment by nathanhleung** [comment] 2016-02-12 20:07
+1

**Comment by shaheenery** [comment] 2016-04-04 21:27
+1

**Comment by Ugoku** [comment] 2016-07-15 10:15
Duplicate of #2070

**Comment by cpplearner** [comment] 2016-09-23 10:30
+1

**Comment by puresick** [comment] 2016-10-13 14:05
+1

**Comment by psimin** [comment] 2016-10-19 02:21
+1

**Comment by cbraith** [comment] 2016-10-24 14:58
+1

**Comment by jineeshjohn** [comment] 2016-11-05 11:15
+1

**Comment by Jeddf** [comment] 2016-11-09 21:10
+1

**Comment by gorsash** [comment] 2016-11-24 16:34
+1

**Comment by oscarmorrison** [comment] 2017-01-13 01:56
+1

**Comment by Connum** [comment] 2017-02-09 14:51
+1

**Comment by pbogdan03** [comment] 2017-02-28 13:23
+1

**Comment by Fyrd** [comment] 2017-03-16 04:44
Now available at http://caniuse.com/#feat=template-literals

**Closed by Fyrd** 2017-03-16 04:44 UTC
Labels: Support data suggestion
