### ISSUE TITLE
I second the request for text-transform. Thanks for your hard work!

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1422] opened 2015-05-12 06:01 UTC
I second the request for text-transform. Thanks for your hard work!

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+4__
Issue added by __Jess__ on __2015-03-12__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment] 2015-05-19 03:53
Duplicate of #1009.

**Closed** 2015-05-19 04:07 UTC
Labels: GM import, Support data suggestion
