### ISSUE TITLE
:first-line pseudo selector

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1226] opened 2015-05-12 05:04 UTC
:first-line pseudo selector

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+6__
Issue added by __pixelcort__ on __2012-03-15__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment] 2015-05-19 03:12
@Fyrd Duplicate of #1109.

**Closed** 2015-05-19 03:52 UTC
Labels: GM import, Support data suggestion
