### ISSUE TITLE
target-new

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1447] opened 2015-05-12 06:04 UTC
target-new

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+3**
Issue added by **Scott Smith** on **2013-01-05**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment] 2015-05-19 08:45
This appears to refer to http://www.w3.org/TR/2004/WD-css3-hyperlinks-20040224/#the-target-new
The latest version has been nuked and states:
> *This specification has been discontinued. At this point no further work is planned.*

**Comment by cvrebert** [comment] 2015-05-25 05:38
@Fyrd Close since nobody seems to have ever implemented this?

**Comment by cgwrench** [comment] 2019-04-05 12:35
This appears to be a duplicate of #1410. Looks like both issues could be closed.

**Closed** 2020-07-03 19:10 UTC
Labels: GM import, Support data suggestion
