### ISSUE TITLE
Add :focus-ring pseudo-class

### ISSUE THREAD

**Issue by nik-garmash** [Fyrd/caniuse#3453] opened 2017-05-22 09:44 UTC
Part of CSS Level 4 standard
https://drafts.csswg.org/selectors-4/#the-focusring-pseudo

**Comment by Ugoku** [comment] 2017-05-22 13:11
+1

**Comment by Fyrd** [comment] 2017-05-26 02:33
Duplicate of the now re-opened #3267

**Closed by Fyrd** 2017-05-26 02:33 UTC
Labels: Duplicate
