### ISSUE TITLE
Track new CSS Text Level 4 wrapping property values

### ISSUE THREAD

**Issue by edgerunner** [Fyrd/caniuse#5547] opened 2020-07-22 10:25 UTC
[CSS Text level 4](https://www.w3.org/TR/css-text-4/#wrapping) has new values for the `word-wrap` and friends. It would be nice to track those.

I'm especially on the lookout for `pretty` and `balance`

**Comment by Fyrd** [comment] 2020-07-26 23:19
Duplicate of #1064

**Closed by Fyrd** 2020-07-26 23:19 UTC
