### ISSUE TITLE
Importmap

### ISSUE THREAD

**Issue by micellius** [Fyrd/caniuse#5221] opened 2019-12-29 06:39 UTC
Starting from Chrome 74, [importmaps](https://www.chromestatus.com/feature/5315286962012160) are supported to resolve bare specifiers of module names. It would be nice to track other browsers support for this feature with [caniuse](https://caniuse.com/).

*Example:*
```html
<script type="importmap">
{
  "imports": {
    "jquery": [ "https://example.com/jquery.mjs" ]
  }
}
</script>
<script type="module">
import "jquery";
</script>
```

[WICG Draft focument](https://wicg.github.io/import-maps/)
[Google Chrome Implementation Design Document](https://docs.google.com/document/d/1vFQzbmxg9ilpg8CT_P8roEYcpTfZ06Q5N4J9-ZQqqZo/edit)

**Comment by Fyrd** [comment] 2020-11-30 18:12
Duplicate of #4810

**Closed by Fyrd** 2020-11-30 18:12 UTC
Labels: Support data suggestion
