### ISSUE TITLE
The 'wbr' element. It'd be great to know which browsers support it, thanks.

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1347] opened 2015-05-12 05:18 UTC
The &#39;wbr&#39; element. It&#39;d be great to know which browsers support it, thanks.

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+4__
Issue added by __Des__ on __2013-03-10__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment] 2015-05-19 04:03
Duplicate of #1032.

**Closed** 2015-05-19 04:07 UTC
Labels: GM import, Support data suggestion
