### ISSUE TITLE
Add createImageBitmap

### ISSUE THREAD

**Issue by castillobgr** [Fyrd/caniuse#2801] opened 2016-09-13 18:19 UTC
[createImageBitmap](https://developer.mozilla.org/en-US/docs/Web/API/ImageBitmapFactories/createImageBitmap) isn't currently available. It'd be cool if it was :)

**Comment by dman777** [comment] 2017-04-06 20:03
Vote +1

**Comment by salarelv** [comment] 2017-05-22 11:47
+1

**Comment by Schweinepriester** [comment] 2017-11-15 19:34
+1

<https://webkit.org/blog/8035/release-notes-for-safari-technology-preview-44/>

> Implemented createImageBitmap() with HTMLCanvasElement

Technically this issue is a duplicate of #2277, as already mentioned there, but this one here has more votes.

Additionally: Subfeature of #2676?

**Comment by Fyrd** [comment] 2018-07-30 05:12
Now available at https://caniuse.com/#feat=createimagebitmap

**Closed by Fyrd** 2018-07-30 05:12 UTC
Labels: Support data suggestion
