### ISSUE TITLE
Two (conflicting) entries for <wbr/>

### ISSUE THREAD

**Issue by maffe** [Fyrd/caniuse#5510] opened 2020-07-01 14:23 UTC
https://caniuse.com/#search=wbr shows two tables for the `wbr` element, with conflicting information (for example, IE 7, Edge 12–18 and Opera 10–11.5 have different support status).

**Comment by Fyrd** [comment] 2020-07-03 05:47
Fixed now, looks like the code removing duplicate MDN tables wasn't working right. I also confirmed the caniuse data seems to be correct for IE & Edge, didn't check Opera since those are really old versions.

**Closed by Fyrd** 2020-07-03 05:47 UTC
